#!/usr/bin/env python3
"""
sync-tokens.py
Generates assets/css/tokens.css from _data/design-tokens.yml.

Usage:
    python3 _tools/sync-tokens.py            # write tokens.css
    python3 _tools/sync-tokens.py --check    # exit 1 if tokens.css is out of date
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
SRC = REPO / "_data" / "design-tokens.yml"
DST = REPO / "assets" / "css" / "tokens.css"

HEADER = """/* ═══════════════════════════════════════════════════════
   SHAYAN SPIEL — DESIGN TOKENS
   GENERATED FROM _data/design-tokens.yml BY _tools/sync-tokens.py
   Do not edit this file directly. Edit the YAML, then run sync.
   ═══════════════════════════════════════════════════════ */

:root {
"""

FOOTER = "}\n"


def render_value(v) -> str:
    """Render a YAML value as a CSS variable value."""
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, str):
        return v
    raise TypeError(f"Unsupported token value type: {type(v).__name__}")


def emit_vars(group: str, items: dict) -> list[str]:
    """Render a group of tokens as CSS custom properties."""
    out = [f"  /* ── {group.title()} ── */"]
    for k, v in items.items():
        if isinstance(v, dict):
            out.append("")
            out.extend(emit_vars(k, v))
            continue
        out.append(f"  --{k}: {render_value(v)};")
    out.append("")
    return out


def build_css(tokens: dict) -> str:
    body_lines: list[str] = []
    for group, items in tokens.items():
        if not isinstance(items, dict):
            continue
        body_lines.extend(emit_vars(group, items))
    body = "\n".join(body_lines).rstrip() + "\n"
    return HEADER + body + FOOTER


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--check", action="store_true",
                   help="exit 1 if tokens.css is out of date (no write)")
    args = p.parse_args()

    if not SRC.exists():
        print(f"error: {SRC} not found", file=sys.stderr)
        return 2

    with SRC.open() as f:
        tokens = yaml.safe_load(f) or {}

    css = build_css(tokens)

    if args.check:
        if not DST.exists() or DST.read_text() != css:
            print(f"out of date: {DST.relative_to(REPO)}")
            return 1
        print("ok")
        return 0

    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text(css)
    print(f"wrote {DST.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
