source "https://rubygems.org"

gem "jekyll", "~> 3.10"
gem "jekyll-feed", "~> 0.17"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-redirect-from", "~> 0.16"
gem "kramdown-parser-gfm"
gem "webrick"
gem "csv"
gem "bigdecimal"
gem "base64"
gem "logger"
