/** @type {import('tailwindcss').Config} */
export default {
  darkMode: [
    "selector",
    '[data-theme="monochrome-dark"], [data-theme="gruvbox-dark"], [data-theme="blue-dark"], [data-theme="discord-dark"], [data-theme="black-gold-dark"]',
  ],
  content: ["./src/**/*.{astro,tsx,ts,html,mdx}"],
  theme: {
    extend: {
      animation: {
        "bounce-subtle": "bounce-subtle 0.6s ease-in-out infinite",
      },
      keyframes: {
        "bounce-subtle": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-3px)" },
        },
      },
      colors: {
        background: "var(--background)",
        "background-deep": "var(--background-deep)",
        panel: "var(--panel)",
        "panel-raised": "var(--panel-raised)",
        "panel-strong": "var(--panel-strong)",
        "panel-deep": "var(--panel-deep)",
        input: "var(--input)",
        hover: "var(--hover)",
        selected: "var(--selected)",
        border: "var(--border)",
        "border-strong": "var(--border-strong)",
        ring: "var(--ring)",
        foreground: "var(--foreground)",
        "foreground-strong": "var(--foreground-strong)",
        "foreground-muted": "var(--foreground-muted)",
        "muted-foreground": "var(--muted-foreground)",
        primary: "var(--primary)",
        "primary-foreground": "var(--primary-foreground)",
        "primary-soft": "var(--primary-soft)",
        success: "var(--success)",
        "success-soft": "var(--success-soft)",
        warning: "var(--warning)",
        "warning-soft": "var(--warning-soft)",
        destructive: "var(--destructive)",
        "destructive-soft": "var(--destructive-soft)",
        info: "var(--info)",
        "info-soft": "var(--info-soft)",
        accent: "var(--accent)",
        "accent-soft": "var(--accent-soft)",
        purple: "var(--purple)",
        "purple-soft": "var(--purple-soft)",
        overlay: "var(--overlay-bg)",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
      },
      boxShadow: {
        panel: "var(--shadow-panel)",
        popover: "var(--shadow-popover)",
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
        mono: ["var(--font-mono)"],
        iransansx: ["var(--font-iransansx)"],
      },
      fontSize: {
        "3xs": ["var(--font-size-3xs)", { lineHeight: "var(--leading-normal)" }],
        "2xs": ["var(--font-size-2xs)", { lineHeight: "var(--leading-normal)" }],
        xs: ["var(--font-size-xs)", { lineHeight: "var(--leading-normal)" }],
        sm: ["var(--font-size-sm)", { lineHeight: "var(--leading-normal)" }],
        base: ["var(--font-size-base)", { lineHeight: "var(--leading-normal)" }],
        lg: ["var(--font-size-lg)", { lineHeight: "var(--leading-normal)" }],
        xl: ["var(--font-size-xl)", { lineHeight: "var(--leading-normal)" }],
        "2xl": ["var(--font-size-2xl)", { lineHeight: "var(--leading-tight)" }],
        "3xl": ["var(--font-size-3xl)", { lineHeight: "var(--leading-tight)" }],
        "4xl": ["var(--font-size-4xl)", { lineHeight: "var(--leading-tight)" }],
        "5xl": ["var(--font-size-5xl)", { lineHeight: "var(--leading-tightest)" }],
        "6xl": ["var(--font-size-6xl)", { lineHeight: "var(--leading-tightest)" }],
        editor: ["var(--font-size-editor)", { lineHeight: "var(--leading-relaxed)" }],
      },
      spacing: {
        "start-1": "var(--spacing-start-1, 0.25rem)",
        "start-2": "var(--spacing-start-2, 0.5rem)",
        "start-3": "var(--spacing-start-3, 0.75rem)",
        "start-4": "var(--spacing-start-4, 1rem)",
        "start-6": "var(--spacing-start-6, 1.5rem)",
        "start-8": "var(--spacing-start-8, 2rem)",
        "end-1": "var(--spacing-end-1, 0.25rem)",
        "end-2": "var(--spacing-end-2, 0.5rem)",
        "end-3": "var(--spacing-end-3, 0.75rem)",
        "end-4": "var(--spacing-end-4, 1rem)",
        "end-6": "var(--spacing-end-6, 1.5rem)",
        "end-8": "var(--spacing-end-8, 2rem)",
      },
    },
  },
  plugins: [require("tailwindcss-rtl")],
};
