/** @type {import('tailwindcss').Config} */
export default {
  darkMode: [
    "selector",
    '[data-theme="monochrome-dark"], [data-theme="gruvbox-dark"], [data-theme="blue-dark"], [data-theme="discord-dark"], [data-theme="black-gold-dark"]',
  ],
  content: ["./src/**/*.{astro,tsx,ts,html,mdx}", "!./src/components/showcase/**"],
  theme: {
    extend: {
      animation: {
        "bounce-subtle": "bounce-subtle 0.6s ease-in-out infinite",
      },
      keyframes: {
        "bounce-subtle": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-3px)" },
        },
      },
      colors: {
        background: "color-mix(in oklab, var(--background) calc(<alpha-value> * 100%), transparent)",
        "background-deep": "color-mix(in oklab, var(--background-deep) calc(<alpha-value> * 100%), transparent)",
        panel: "color-mix(in oklab, var(--panel) calc(<alpha-value> * 100%), transparent)",
        "panel-raised": "color-mix(in oklab, var(--panel-raised) calc(<alpha-value> * 100%), transparent)",
        "panel-strong": "color-mix(in oklab, var(--panel-strong) calc(<alpha-value> * 100%), transparent)",
        "panel-deep": "color-mix(in oklab, var(--panel-deep) calc(<alpha-value> * 100%), transparent)",
        input: "color-mix(in oklab, var(--input) calc(<alpha-value> * 100%), transparent)",
        hover: "color-mix(in oklab, var(--hover) calc(<alpha-value> * 100%), transparent)",
        selected: "color-mix(in oklab, var(--selected) calc(<alpha-value> * 100%), transparent)",
        border: "color-mix(in oklab, var(--border) calc(<alpha-value> * 100%), transparent)",
        "border-strong": "color-mix(in oklab, var(--border-strong) calc(<alpha-value> * 100%), transparent)",
        ring: "color-mix(in oklab, var(--ring) calc(<alpha-value> * 100%), transparent)",
        foreground: "color-mix(in oklab, var(--foreground) calc(<alpha-value> * 100%), transparent)",
        "foreground-strong": "color-mix(in oklab, var(--foreground-strong) calc(<alpha-value> * 100%), transparent)",
        "foreground-muted": "color-mix(in oklab, var(--foreground-muted) calc(<alpha-value> * 100%), transparent)",
        "muted-foreground": "color-mix(in oklab, var(--muted-foreground) calc(<alpha-value> * 100%), transparent)",
        primary: "color-mix(in oklab, var(--primary) calc(<alpha-value> * 100%), transparent)",
        "primary-foreground": "color-mix(in oklab, var(--primary-foreground) calc(<alpha-value> * 100%), transparent)",
        "primary-soft": "color-mix(in oklab, var(--primary-soft) calc(<alpha-value> * 100%), transparent)",
        success: "color-mix(in oklab, var(--success) calc(<alpha-value> * 100%), transparent)",
        "success-soft": "color-mix(in oklab, var(--success-soft) calc(<alpha-value> * 100%), transparent)",
        warning: "color-mix(in oklab, var(--warning) calc(<alpha-value> * 100%), transparent)",
        "warning-soft": "color-mix(in oklab, var(--warning-soft) calc(<alpha-value> * 100%), transparent)",
        destructive: "color-mix(in oklab, var(--destructive) calc(<alpha-value> * 100%), transparent)",
        "destructive-soft": "color-mix(in oklab, var(--destructive-soft) calc(<alpha-value> * 100%), transparent)",
        info: "color-mix(in oklab, var(--info) calc(<alpha-value> * 100%), transparent)",
        "info-soft": "color-mix(in oklab, var(--info-soft) calc(<alpha-value> * 100%), transparent)",
        accent: "color-mix(in oklab, var(--accent) calc(<alpha-value> * 100%), transparent)",
        "accent-soft": "color-mix(in oklab, var(--accent-soft) calc(<alpha-value> * 100%), transparent)",
        purple: "color-mix(in oklab, var(--purple) calc(<alpha-value> * 100%), transparent)",
        "purple-soft": "color-mix(in oklab, var(--purple-soft) calc(<alpha-value> * 100%), transparent)",
        overlay: "color-mix(in oklab, var(--overlay-bg) calc(<alpha-value> * 100%), transparent)",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        full: "9999px",
      },
      boxShadow: {
        panel: "var(--shadow-panel)",
        popover: "var(--shadow-popover)",
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
        mono: ["var(--font-mono)"],
        iransansx: ["var(--font-iransansx)"],
      },
      fontSize: {
        "3xs": ["var(--font-size-3xs)", { lineHeight: "var(--leading-normal)" }],
        "2xs": ["var(--font-size-2xs)", { lineHeight: "var(--leading-normal)" }],
        xs: ["var(--font-size-xs)", { lineHeight: "var(--leading-normal)" }],
        sm: ["var(--font-size-sm)", { lineHeight: "var(--leading-normal)" }],
        base: ["var(--font-size-base)", { lineHeight: "var(--leading-normal)" }],
        lg: ["var(--font-size-lg)", { lineHeight: "var(--leading-normal)" }],
        xl: ["var(--font-size-xl)", { lineHeight: "var(--leading-normal)" }],
        "2xl": ["var(--font-size-2xl)", { lineHeight: "var(--leading-tight)" }],
        "3xl": ["var(--font-size-3xl)", { lineHeight: "var(--leading-tight)" }],
        "4xl": ["var(--font-size-4xl)", { lineHeight: "var(--leading-tight)" }],
        "5xl": ["var(--font-size-5xl)", { lineHeight: "var(--leading-tightest)" }],
        "6xl": ["var(--font-size-6xl)", { lineHeight: "var(--leading-tightest)" }],
        editor: ["var(--font-size-editor)", { lineHeight: "var(--leading-relaxed)" }],
      },
      spacing: {
        "start-1": "var(--spacing-start-1, 0.25rem)",
        "start-2": "var(--spacing-start-2, 0.5rem)",
        "start-3": "var(--spacing-start-3, 0.75rem)",
        "start-4": "var(--spacing-start-4, 1rem)",
        "start-6": "var(--spacing-start-6, 1.5rem)",
        "start-8": "var(--spacing-start-8, 2rem)",
        "end-1": "var(--spacing-end-1, 0.25rem)",
        "end-2": "var(--spacing-end-2, 0.5rem)",
        "end-3": "var(--spacing-end-3, 0.75rem)",
        "end-4": "var(--spacing-end-4, 1rem)",
        "end-6": "var(--spacing-end-6, 1.5rem)",
        "end-8": "var(--spacing-end-8, 2rem)",
      },
    },
  },
  plugins: [require("tailwindcss-rtl")],
};
