import { LocalizedContent } from './Localization';
import { SurfaceIcon, Providers } from './ComponentSurface';
const roles = [
    { name: 'Business analyst', icon: 'search', tone: 'success', verb: 'Understand the work', tools: ['notion', 'trello'], output: 'Process map · opportunity brief' },
    { name: 'AI architect', icon: 'layer', tone: 'accent', verb: 'Design the system', tools: ['openai-chatgpt', 'claude-code'], output: 'Architecture · model & tool choices' },
    { name: 'Agent engineer', icon: 'code-alt', tone: 'warning', verb: 'Build the capability', tools: ['codex', 'n8n', 'python'], output: 'Agents · workflows · integrations' },
    { name: 'Evals engineer', icon: 'pulse', tone: 'primary', verb: 'Prove the outcome', tools: ['langsmith-langchain', 'langfuse'], output: 'Quality gates · traces · business impact' },
];
function RolePreview({ index }: {
    index: number;
}) {
    if (index === 0)
        return <div className="team-map-preview"><span><LocalizedContent value={"Request"}/></span><i><LocalizedContent value={"\u2192"}/></i><span><LocalizedContent value={"Resolve"}/></span><i><LocalizedContent value={"\u2192"}/></i><span><LocalizedContent value={"Outcome"}/></span><svg viewBox="0 0 240 36"><path d="M20 6 H220 M20 6 V25 H80 M220 6 V25 H160"/></svg><small><LocalizedContent value={"Map handoffs. Find the bottleneck."}/></small></div>;
    if (index === 1)
        return <div className="team-stack-preview"><span><LocalizedContent value={"Company context"}/></span><span><LocalizedContent value={"Harness + memory"}/></span><span><LocalizedContent value={"Tools + guardrails"}/></span></div>;
    if (index === 2)
        return <div className="team-code-preview"><span><i><LocalizedContent value={"01"}/></i><LocalizedContent value={" workflow.run(request)"}/></span><span><i><LocalizedContent value={"02"}/></i><LocalizedContent value={" await agent.execute()"}/></span><span><i><LocalizedContent value={"03"}/></i><LocalizedContent value={" assert quality.passed"}/></span><b><LocalizedContent value={"\u2713 build & checks passed"}/></b></div>;
    return <div className="team-evals-preview"><LocalizedContent value={[['Correctness', '96'], ['Policy', '100'], ['Task success', '93']].map(([label, n]) => <div key={label}><span><LocalizedContent value={label}/></span><i><b style={{ width: `${n}%` }}/></i><small><LocalizedContent value={n}/><LocalizedContent value={"%"}/></small></div>)}/></div>;
}
export function TeamAssembly() {
    return <div className="team-assembly">
    <div className="team-accountable"><div className="team-manager"><span className="premium-icon"><SurfaceIcon name="group"/></span><div><small><LocalizedContent value={"TRANSFORMATION LEADERSHIP"}/></small><strong><LocalizedContent value={"Manager"}/></strong></div></div><div><b><LocalizedContent value={"Set priorities"}/></b><span><LocalizedContent value={"Business value first"}/></span></div><div><b><LocalizedContent value={"Connect the system"}/></b><span><LocalizedContent value={"One shared architecture"}/></span></div><div><b><LocalizedContent value={"Measure outcomes"}/></b><span><LocalizedContent value={"Evidence for every decision"}/></span></div></div>
    <div className="team-rail"><span><LocalizedContent value={"One team. Four complementary disciplines."}/></span></div>
    <div className="team-specialists"><LocalizedContent value={roles.map((r, i) => <section key={r.name} className={`premium-panel tone-${r.tone}`}><div className="specialist-heading"><span className="premium-icon"><SurfaceIcon name={r.icon}/></span><div><small><LocalizedContent value={"0"}/><LocalizedContent value={i + 1}/><LocalizedContent value={" / "}/><LocalizedContent value={r.verb}/></small><strong><LocalizedContent value={r.name}/></strong></div></div><RolePreview index={i}/><p><LocalizedContent value={r.output}/></p><Providers logos={r.tools}/></section>)}/></div>
    <div className="team-department-label"><span><LocalizedContent value={"BUSINESS TEAMS OWN THEIR OUTCOMES"}/></span><b><LocalizedContent value={"Shared capability \u2192 every department"}/></b></div>
    <div className="team-departments"><LocalizedContent value={[['Sales', 'Lead → opportunity', 'salesforce', 'group'], ['Support', 'Request → resolution', 'zendesk', 'support'], ['Marketing', 'Brief → campaign', 'claude-code', 'trending-up'], ['Finance', 'Invoice → approval', 'python', 'receipt'], ['Operations', 'Work → delivery', 'n8n', 'cog'], ['HR', 'Join → onboard', 'notion', 'group']].map(([name, work, logo, icon]) => <section key={name}><SurfaceIcon name={icon}/><strong><LocalizedContent value={name}/></strong><span><LocalizedContent value={work}/></span><Providers logos={[logo]}/></section>)}/></div>
    </div>;
}
function RunToolbar({ title, detail }: {
    title: string;
    detail: string;
}) { return <div className="run-toolbar"><span><img src="/assets/logos/icon-transparent.svg" alt=""/><b><LocalizedContent value={"SpielOS"}/></b><i><LocalizedContent value={"/"}/></i><LocalizedContent value={title}/></span><small><LocalizedContent value={detail}/></small><em><LocalizedContent value={"\u25CF Complete"}/></em></div>; }
export function HarnessAssembly() {
    return <div className="harness-workspace premium-panel">
    <RunToolbar title="Harness / support-resolution" detail="ILLUSTRATIVE RUN · 0184"/>
    <div className="harness-columns">
        <section className="harness-input"><div className="workspace-section-label"><LocalizedContent value={"01 / INPUT + CONTEXT"}/></div><div className="mini-composer"><Providers logos={['codex']}/><strong><LocalizedContent value={"Resolve a delivery exception."}/></strong><p><LocalizedContent value={"Check the order, apply the delivery policy and prepare a reply."}/></p><div><span><LocalizedContent value={"\uFF0B Attach context"}/></span><b><LocalizedContent value={"\u2191"}/></b></div></div><div className="context-attachments"><span><SurfaceIcon name="file"/><b><LocalizedContent value={"delivery-policy.md"}/></b><small><LocalizedContent value={"verified"}/></small></span><span><SurfaceIcon name="data"/><b><LocalizedContent value={"Order #1042"}/></b><small><LocalizedContent value={"current"}/></small></span><span><SurfaceIcon name="shield"/><b><LocalizedContent value={"Escalation rules"}/></b><small><LocalizedContent value={"required"}/></small></span></div></section>
        <section className="harness-engine"><div className="workspace-section-label"><LocalizedContent value={"02 / AGENT RUNTIME"}/></div><div className="engine-cycle"><svg viewBox="0 0 500 190" aria-hidden="true"><path className="engine-future" d="M168 95 A82 82 0 1 1 332 95 A82 82 0 1 1 168 95"/><path d="M168 95 A82 82 0 0 1 326 64 M332 95 A82 82 0 0 1 174 126"/><path d="m311 60 15 4-3-15 M188 130l-14-4 2 15"/></svg><span className="engine-reason"><SurfaceIcon name="brain"/><b><LocalizedContent value={"Reason"}/></b></span><span className="engine-observe"><SurfaceIcon name="search"/><b><LocalizedContent value={"Observe"}/></b></span><div><small><LocalizedContent value={"BOUNDED EXECUTION"}/></small><strong><LocalizedContent value={"Agent loop"}/></strong><span><LocalizedContent value={"Until verified completion"}/></span></div></div><div className="tool-call-log"><div><span className="tool-call-name"><LocalizedContent value={"\u21B3 order_status"}/></span><code><LocalizedContent value={'{ order_id: "1042" }'}/></code><b><LocalizedContent value={"680 ms"}/></b></div><div><span className="tool-call-name"><LocalizedContent value={"\u21B3 policy_search"}/></span><code><LocalizedContent value={'{ topic: "delivery" }'}/></code><b><LocalizedContent value={"420 ms"}/></b></div><footer><Providers logos={['activepieces', 'python', 'claude-code']}/><span><LocalizedContent value={"Tools & specialist workers"}/></span></footer></div></section>
        <section className="harness-output"><div className="workspace-section-label"><LocalizedContent value={"03 / VERIFY + DELIVER"}/></div><div className="quality-gates"><strong><SurfaceIcon name="shield"/><LocalizedContent value={"Guardrails"}/></strong><LocalizedContent value={['Grounded in evidence', 'Company policy respected', 'Required work complete'].map(s => <span key={s}><i><LocalizedContent value={"\u2713"}/></i><LocalizedContent value={s}/></span>)}/></div><div className="reply-artifact"><span><LocalizedContent value={"\u2713 VERIFIED RESULT"}/></span><strong><LocalizedContent value={"Customer reply ready"}/></strong><p><LocalizedContent value={"Order status explained. Next action confirmed. Escalation attached if required."}/></p><footer><SurfaceIcon name="file"/><LocalizedContent value={"reply.md "}/><b><LocalizedContent value={"ready for review"}/></b></footer></div></section>
    </div><div className="harness-waterfall"><div><SurfaceIcon name="pulse"/><strong><LocalizedContent value={"Every step leaves a trace"}/></strong><span><LocalizedContent value={"Context \u00B7 model \u00B7 tools \u00B7 checks \u00B7 artifacts"}/></span></div><div className="waterfall-mini"><LocalizedContent value={[18, 44, 26, 13, 20].map((n, i) => <span key={i} style={{ width: `${n}%`, marginLeft: `${i * 13}%` }}/>)}/></div><dl><div><dt><LocalizedContent value={"LATENCY"}/></dt><dd><LocalizedContent value={"2.84 s"}/></dd></div><div><dt><LocalizedContent value={"QUALITY"}/></dt><dd><LocalizedContent value={"0.96"}/></dd></div><div><dt><LocalizedContent value={"ERRORS"}/></dt><dd><LocalizedContent value={"0"}/></dd></div></dl></div>
    </div>;
}
export function MemoryAssembly() {
    return <div className="memory-workspace">
    <div className="memory-library"><div className="workspace-section-label"><LocalizedContent value={"01 / COMPANY MEMORY"}/></div><LocalizedContent value={[['procedural', 'book-open', 'How to do it', 'Delivery exception playbook', 'Procedure · approved v3'], ['semantic', 'data', 'What is true', 'Delivery policy & product facts', 'Knowledge · source linked'], ['episodic', 'history', 'What happened', 'Resolved support run / 0183', 'Experience · reviewed lesson']].map(([id, icon, title, record, meta]) => <section className={`memory-source memory-source--${id}`} key={id}><span className="premium-icon"><SurfaceIcon name={icon}/></span><div><small><LocalizedContent value={id.toUpperCase()}/></small><strong><LocalizedContent value={title}/></strong><p><LocalizedContent value={record}/></p><footer><LocalizedContent value={meta}/></footer></div></section>)}/></div>
    <div className="memory-retrieval premium-panel"><div className="workspace-section-label"><LocalizedContent value={"02 / CONTEXT BUILDER"}/></div><strong><LocalizedContent value={"Retrieve. Select. Compose."}/></strong><div className="retrieval-search"><SurfaceIcon name="search"/><span><LocalizedContent value={"Resolve delivery exception #1042"}/></span></div><div className="retrieval-results"><LocalizedContent value={[['Delivery exception playbook', '0.98', 'METHOD'], ['Approved delivery policy', '0.96', 'FACT'], ['Previous resolved exception', '0.91', 'LESSON']].map(([s, n, t]) => <div key={s}><SurfaceIcon name="file"/><span><LocalizedContent value={s}/><small><LocalizedContent value={t}/></small></span><b><LocalizedContent value={n}/></b></div>)}/></div><div className="context-budget"><span><LocalizedContent value={"Working context "}/><b><LocalizedContent value={"2,480 tokens"}/></b></span><div><i /><i /><i /></div><small><LocalizedContent value={"Only the relevant sources, with their boundaries."}/></small></div><div className="composed-context"><small><LocalizedContent value={"COMPOSED BRIEF \u2192 HARNESS"}/></small><span><LocalizedContent value={"Request + facts + method + useful history"}/></span></div></div>
    <div className="memory-learning"><div className="workspace-section-label"><LocalizedContent value={"03 / APPLY + LEARN"}/></div><section className="memory-agent premium-panel"><span className="premium-icon"><SurfaceIcon name="brain"/></span><strong><LocalizedContent value={"Run with context"}/></strong><div className="memory-agent-steps"><span><LocalizedContent value={"Reason"}/></span><i><LocalizedContent value={"\u2192"}/></i><span><LocalizedContent value={"Act"}/></span><i><LocalizedContent value={"\u2192"}/></i><span><LocalizedContent value={"Observe"}/></span></div><p><LocalizedContent value={"Execute through the harness."}/><br /><LocalizedContent value={"Verify the business result."}/></p></section><div className="memory-save"><small><LocalizedContent value={"EPISODE / 0184"}/></small><strong><LocalizedContent value={"A useful lesson, retained."}/></strong><p><LocalizedContent value={"Capture the decision, its outcome and what should improve next time."}/></p><span><i><LocalizedContent value={"\u2713"}/></i><LocalizedContent value={"Reviewed before reuse"}/></span></div></div>
    <div className="memory-return"><span><LocalizedContent value={"\u21B6"}/></span><b><LocalizedContent value={"Review the outcome \u2192 update the method or knowledge \u2192 improve the next run"}/></b><SurfaceIcon name="refresh"/></div>
    </div>;
}
