/**
 * Workflow solution pages — /solutions/workflows/[slug]/
 *
 * One search intent = one strong commercial page. Copy is written around the
 * actual operational workflow, never generated by swapping nouns in a shared
 * paragraph. Shared template lives at src/pages/solutions/workflows/[slug].astro.
 */

export interface WorkflowFaq { q: string; a: string }
export interface WorkflowAutomate { title: string; desc: string }

export interface WorkflowSolution {
  slug: string;
  name: string;
  eyebrow: string;
  h1: string;
  heroCopy: string;
  /** The concrete manual chain shown as a vertical step list. */
  manualSteps: string[];
  painPoint: string;
  beforeText: string;
  withText: string;
  /** Actual states/actions rendered as an arrow flow. */
  flowStates: string[];
  /** Matching boxicon per flow state. */
  flowIcons: string[];
  automateIntro: string;
  automate: WorkflowAutomate[];
  /** SOFTWARE_SOLUTIONS keys this workflow typically runs on. */
  toolKeys: string[];
  audiences: { name: string; note: string }[];
  /** Other workflow slugs to cross-link. */
  relatedWorkflows: string[];
  /** Department slugs under /solutions/ai-departments/. */
  relatedDepartments: string[];
  boundaryIntro: string;
  runsAlone: string[];
  stopsForHuman: string[];
  faqs: WorkflowFaq[];
  seoTitle: string;
  seoDesc: string;
}

export const WORKFLOW_SOLUTIONS: WorkflowSolution[] = [
  {
    slug: "client-onboarding-automation",
    name: "Client Onboarding Automation",
    eyebrow: "CLIENT ONBOARDING AUTOMATION",
    h1: "Automate client onboarding without managing every step.",
    heroCopy:
      "When a client signs, SpielOS can collect their information, request documents, create records, prepare your team, follow up on missing items, and keep the process moving — without someone manually working a checklist for every new client.",
    manualSteps: [
      "Contract signed → send welcome email by hand",
      "Write the same intake request again for each client",
      "Wait — then notice nothing arrived",
      "Chase missing information and documents",
      "Create folders, records, and project entries one by one",
      "Update the CRM so everyone else knows what happened",
      "Notify the team and schedule the kickoff",
    ],
    painPoint:
      "The problem isn't that any one step is difficult. Someone has to remember and coordinate all of them — for every single client, forever.",
    beforeText:
      "Someone checks what happened after signing, remembers the next step, sends the next message, and hopes nothing slips while they juggle other clients.",
    withText:
      "The workflow watches the onboarding state itself. It sends what should be sent, collects what should be collected, updates your systems, and brings you in only when a judgment call or exception needs a person.",
    flowStates: ["Contract signed", "Welcome sent", "Intake requested", "Documents tracked", "Records created", "Team notified", "Kickoff scheduled"],
    flowIcons: ["bx-check-square","bx-envelope","bx-task","bx-folder-open","bx-data","bx-bell","bx-calendar"],
    automateIntro: "What client onboarding automation handles end-to-end:",
    automate: [
      { title: "Send welcome and intake requests", desc: "Personalized to the client and engagement type the moment the deal is marked won." },
      { title: "Collect client information", desc: "Structured intake forms and email replies captured into clean fields." },
      { title: "Request required documents", desc: "The right document list per engagement, tracked received vs. outstanding." },
      { title: "Detect missing items", desc: "Knows exactly what is still open without anyone re-checking." },
      { title: "Follow up until complete", desc: "Polite, well-timed reminders that stop the moment the client responds." },
      { title: "Create CRM and project records", desc: "Folders, tasks, and database entries created consistently every time." },
      { title: "Prepare the team handoff", desc: "An internal summary of who the client is and what they need, ready before kickoff." },
      { title: "Escalate exceptions", desc: "Unusual answers, stalled clients, or special requests go to a person immediately." },
    ],
    toolKeys: ["gmail", "hubspot", "attio", "google-drive", "notion", "google-calendar"],
    audiences: [
      { name: "Agencies & consultancies", note: "Recurring onboarding per client, high coordination cost." },
      { name: "Accounting & professional services", note: "Document-heavy intake with strict completeness requirements." },
      { name: "Recruitment & staffing firms", note: "Client and placement onboarding running in parallel." },
    ],
    relatedWorkflows: ["document-collection-automation", "follow-up-automation", "data-entry-automation"],
    relatedDepartments: ["marketing", "content"],
    boundaryIntro:
      "Onboarding sets the tone of the whole relationship, so the boundary line matters. SpielOS automates the coordination and keeps the relationship with you.",
    runsAlone: [
      "Standard welcome and intake communications from approved templates",
      "Document tracking, reminders, and completeness checks",
      "Record, folder, and task creation across your systems",
      "Internal summaries and team notifications",
      "Kickoff scheduling against your calendar rules",
    ],
    stopsForHuman: [
      "Anything a client says that changes scope, price, or expectations",
      "Unusual document situations and exceptions",
      "The kickoff conversation itself",
    ],
    faqs: [
      { q: "What is client onboarding automation?", a: "It is a workflow that runs the administrative side of onboarding — welcome messages, information collection, document tracking, record creation, and team notification — automatically, instead of a person coordinating each step by hand." },
      { q: "Can AI follow up with clients automatically?", a: "Yes, within rules you approve. Follow-ups are sent on a sensible schedule, personalized to the engagement, and stop as soon as the client responds. Anything sensitive escalates to a human." },
      { q: "Can this work with our existing CRM and email?", a: "Yes. That is the default. SpielOS works on top of the CRM, email, drive, and messaging tools you already use rather than replacing them." },
      { q: "Does automated onboarding replace our account manager?", a: "No. It removes the checklist management so your account manager spends onboarding time talking to the client, not copying data and chasing documents." },
    ],
    seoTitle: "Client Onboarding Automation | SpielOS",
    seoDesc: "Automate client onboarding: welcome messages, intake, document collection, CRM records, and team handoff — run on the tools you already use.",
  },
  {
    slug: "data-entry-automation",
    name: "Data Entry Automation",
    eyebrow: "DATA ENTRY AUTOMATION",
    h1: "Stop moving the same data between systems by hand.",
    heroCopy:
      "Every email, form, PDF, and spreadsheet that arrives still ends up retyped into your CRM, database, or accounting tool. SpielOS reads incoming information, extracts the right fields, validates them, and puts them where they belong — with the source kept for checking.",
    manualSteps: [
      "Open the email, form response, or attachment",
      "Read it and find the fields that matter",
      "Switch to the CRM, sheet, or system",
      "Retype the values — hoping nothing is mistyped",
      "Notice a duplicate or contradiction halfway through",
      "Fix the format someone else will complain about later",
      "Repeat dozens of times a day",
    ],
    painPoint:
      "No individual entry is hard. But the volume compounds: retyping is slow, error-prone, invisible in cost reports, and it is the work nobody was hired to do.",
    beforeText:
      "A person is the copy-paste layer between your inbox and your systems — and the quality control layer too, usually at the same time.",
    withText:
      "Incoming information is read, structured, validated, and written to the right system automatically. Uncertain entries are flagged for review instead of silently guessed, and every value keeps a link back to its source.",
    flowStates: ["Item arrives", "Fields extracted", "Data validated", "Duplicates checked", "Systems updated", "Uncertain flagged", "Source archived"],
    flowIcons: ["bx-download","bx-search-alt","bx-check-square","bx-copy","bx-data","bx-error","bx-archive"],
    automateIntro: "What data entry automation takes off your team:",
    automate: [
      { title: "Read emails, forms, and documents", desc: "Invoices, intake forms, applications, order confirmations — structured or messy." },
      { title: "Extract relevant fields", desc: "Names, amounts, dates, IDs, addresses — mapped to your schema." },
      { title: "Validate required data", desc: "Missing or malformed values are caught before they enter your systems." },
      { title: "Normalize formats", desc: "Dates, phone numbers, currencies, and naming conventions standardized on the way in." },
      { title: "Detect duplicates", desc: "Cross-checks existing records so the same lead or invoice is not entered twice." },
      { title: "Update CRM, sheets, and databases", desc: "Written directly to the systems you already use, in the fields you already have." },
      { title: "Flag uncertain entries", desc: "Low-confidence extractions queue for quick human review instead of corrupting data." },
      { title: "Preserve source evidence", desc: "Every stored value links back to the original email or document it came from." },
    ],
    toolKeys: ["gmail", "attio", "hubspot", "notion", "google-drive", "zapier"],
    audiences: [
      { name: "Operations teams", note: "High volume of forms, orders, and confirmations daily." },
      { name: "Sales & CRM owners", note: "Lead and contact data arriving from many channels." },
      { name: "Finance & back office", note: "Invoices and statements that must land in accounting correctly." },
    ],
    relatedWorkflows: ["invoice-processing-automation", "lead-qualification-automation", "client-intake-automation"],
    relatedDepartments: ["analytics", "seo"],
    boundaryIntro:
      "Bad data is more expensive than slow data. So the automation writes confidently only when it is confident — and asks otherwise.",
    runsAlone: [
      "Extraction and normalization of standard, recurring formats",
      "Duplicate checks and cross-references against existing records",
      "Direct writes for high-confidence matches",
      "Archiving source documents with every entry",
    ],
    stopsForHuman: [
      "Ambiguous or low-confidence values — queued for review, never guessed",
      "Conflicting records that need a business decision",
      "New document types until the pattern is taught once",
    ],
    faqs: [
      { q: "What is data entry automation?", a: "It is software that reads incoming emails, forms, and documents, extracts the relevant fields, validates them, and writes them into your CRM, spreadsheets, or databases automatically — keeping the source linked to every value." },
      { q: "Will AI make mistakes entering our data?", a: "It can — which is why uncertain extractions are flagged for a quick human check instead of being written blindly. High-confidence standard formats are entered directly; anything ambiguous waits for review." },
      { q: "Do we need to change our CRM or tools?", a: "No. The automation writes into the systems you already use. Migration is not part of the offer." },
      { q: "How is this different from Zapier?", a: "Zapier moves data between defined triggers and fields. Data entry automation reads unstructured input — emails, PDFs, scans — decides what matters, validates it, and handles the exceptions that break rigid zaps." },
    ],
    seoTitle: "Data Entry Automation | Stop Retyping Between Systems | SpielOS",
    seoDesc: "Data entry automation that reads emails, forms, and documents, extracts and validates fields, and updates your CRM and systems — sources preserved.",
  },
  {
    slug: "follow-up-automation",
    name: "Follow-Up Automation",
    eyebrow: "FOLLOW-UP AUTOMATION",
    h1: "Never lose a thread because someone forgot to follow up.",
    heroCopy:
      "Leads, clients, documents, quotes, approvals — something is always waiting on a reply. SpielOS tracks what is actually outstanding, sends the right follow-up at the right time, stops the moment someone responds, and escalates the cases that need a person.",
    manualSteps: [
      "Remember (or forget) who was supposed to reply",
      "Check the thread to see what was already said",
      "Draft yet another nudge — politely, again",
      "Guess how long to wait before sending it",
      "Discover the deal died because nobody followed up twice",
      "Apologize to the client whose document request slipped",
      "Keep a mental list of everything still open",
    ],
    painPoint:
      "Follow-up is memory work. It dies quietly whenever people get busy — and the cost shows up weeks later as stalled deals, late projects, and awkward apologies.",
    beforeText:
      "Follow-ups live in inboxes, notes, and someone's head. Whether they happen depends on who is busiest that week.",
    withText:
      "Outstanding items are tracked as workflow state. The system knows what was asked, when, and whether a response arrived — and follows up accordingly, updating records and escalating what goes cold.",
    flowStates: ["Request sent", "Waiting tracked", "Response watched", "Reminder timed", "Thread resumed", "Status updated", "Overdue escalated"],
    flowIcons: ["bx-send","bx-time-five","bx-show","bx-bell","bx-comment-detail","bx-refresh","bx-error"],
    automateIntro: "What follow-up automation covers:",
    automate: [
      { title: "Detect what is outstanding", desc: "Leads, client replies, documents, quote approvals, internal sign-offs — tracked as state, not memory." },
      { title: "Understand current context", desc: "Reads the thread so the follow-up continues the conversation instead of restarting it." },
      { title: "Send appropriate follow-ups", desc: "Right tone, right channel, referencing what was actually requested." },
      { title: "Stop when someone responds", desc: "The moment a reply lands, reminders stop and the workflow moves forward." },
      { title: "Adapt timing to state", desc: "Hot lead vs. overdue invoice get different cadences, defined by your rules." },
      { title: "Update CRM and task status", desc: "Every touch recorded so the pipeline reflects reality." },
      { title: "Escalate overdue or unusual cases", desc: "Stalled or sensitive threads surface to a person with full context attached." },
    ],
    toolKeys: ["gmail", "slack", "hubspot", "attio", "telegram", "whatsapp"],
    audiences: [
      { name: "Sales teams", note: "Pipeline leaks happen between touches, not during them." },
      { name: "Agencies & service firms", note: "Client-side dependencies stall delivery constantly." },
      { name: "Recruitment firms", note: "Candidates, clients, and document chases all in parallel." },
    ],
    relatedWorkflows: ["client-onboarding-automation", "document-collection-automation", "lead-qualification-automation"],
    relatedDepartments: ["marketing", "content"],
    boundaryIntro:
      "A bad follow-up costs more than a missed one. Tone rules and escalation lines are yours to define — and the machine stays inside them.",
    runsAlone: [
      "Routine nudges for documents, approvals, and unanswered requests",
      "State-based cadences you define per case type",
      "CRM and task updates after every touch",
      "Stopping instantly when a human conversation begins",
    ],
    stopsForHuman: [
      "Sensitive conversations — complaints, negotiations, bad news",
      "Any thread where the reply changes terms or expectations",
      "Escalations after a case goes quiet too long",
    ],
    faqs: [
      { q: "What does follow-up automation do?", a: "It tracks everything waiting on a response — leads, clients, documents, approvals — and sends appropriate reminders until resolved, stopping automatically when someone replies." },
      { q: "Will automated follow-ups sound robotic?", a: "They are drafted from your templates and the actual thread context, so they reference the real request. You approve tone rules up front, and anything sensitive routes to a person." },
      { q: "Does it cover leads, clients, and internal follow-ups?", a: "Yes — lead, client, document, quote, and internal approval follow-ups all run on the same state-tracking engine with different rules per type." },
      { q: "How does it know when to stop following up?", a: "When a response arrives, when you mark the case handled, or when your escalation rule says a person should take over." },
    ],
    seoTitle: "Follow-Up Automation | Leads, Clients & Documents | SpielOS",
    seoDesc: "Follow-up automation that tracks every outstanding reply — leads, clients, documents, approvals — and follows up until it's done. No thread forgotten.",
  },
  {
    slug: "client-intake-automation",
    name: "Client Intake Automation",
    eyebrow: "CLIENT INTAKE AUTOMATION",
    h1: "Turn incoming inquiries into qualified, routed, ready-to-work requests.",
    heroCopy:
      "New requests arrive by form, email, and referral — half-finished and unstructured. SpielOS captures them, extracts what is actually being asked, asks the missing questions, files everything in your CRM, and routes it to the right person with a summary already written.",
    manualSteps: [
      "Notice the inquiry arrived in three places at once",
      "Read it and figure out what they actually need",
      "Email back asking the questions they forgot to answer",
      "Copy details into the CRM imperfectly",
      "Decide who should handle it — from memory",
      "Brief that person manually",
      "Lose track of the ones that never got a reply",
    ],
    painPoint:
      "Intake is where work enters your company — and it is usually the least engineered process in it. Slow or sloppy intake loses clients before the work even starts.",
    beforeText:
      "Whoever sees the inquiry first becomes the intake process: reading, replying, filing, routing, and remembering to circle back.",
    withText:
      "Every inquiry is captured the same way: structured, completed, categorized, filed, and routed with an internal summary — so the first human conversation happens with context already prepared.",
    flowStates: ["Inquiry arrives", "Requirements extracted", "Gaps asked", "Docs collected", "Categorized", "Routed to owner", "Summary ready"],
    flowIcons: ["bx-envelope-open","bx-search-alt","bx-help-circle","bx-folder-open","bx-collection","bx-network-chart","bx-file"],
    automateIntro: "What client intake automation handles:",
    automate: [
      { title: "Capture inquiries from any channel", desc: "Forms, forwarded emails, referrals — one consistent intake pipeline." },
      { title: "Extract structured requirements", desc: "What they need, when, budget signals, constraints — pulled out of free text." },
      { title: "Ask the missing questions", desc: "Targeted follow-ups that complete the picture without embarrassing reply chains." },
      { title: "Collect relevant documents", desc: "The right files requested and tracked from day one." },
      { title: "Qualify or categorize requests", desc: "Sorted against your criteria: fit, urgency, service type." },
      { title: "Create and update CRM records", desc: "Clean records created automatically — no transcription step." },
      { title: "Route to the correct person", desc: "By service line, workload, or rule — not by whoever noticed first." },
      { title: "Prepare the internal summary", desc: "Who they are, what they need, what is still open — before the first call." },
    ],
    toolKeys: ["gmail", "hubspot", "attio", "notion", "slack", "google-drive"],
    audiences: [
      { name: "Professional services firms", note: "Every engagement starts with an unstructured inquiry." },
      { name: "Agencies", note: "Mixed inbound: retainers, projects, one-off requests." },
      { name: "Accounting & legal practices", note: "Compliance-sensitive intake that must be complete." },
    ],
    relatedWorkflows: ["lead-qualification-automation", "client-onboarding-automation", "document-collection-automation"],
    relatedDepartments: ["marketing", "analytics"],
    boundaryIntro:
      "First impressions decide whether inquiries become clients. Intake automation handles the paperwork around that first impression — you keep the conversation.",
    runsAlone: [
      "Capturing, structuring, and completing inquiry information",
      "Document requests and tracking",
      "CRM creation and routing by your rules",
      "Internal briefs prepared before anyone picks up the phone",
    ],
    stopsForHuman: [
      "The first real conversation with the prospective client",
      "Fit judgments your rules cannot express",
      "Red-flag situations that need a partner's eye",
    ],
    faqs: [
      { q: "What is client intake automation?", a: "It is a workflow that captures every incoming inquiry, extracts the actual requirement, completes missing information, files it in your CRM, and routes it to the right person with a prepared summary." },
      { q: "Will clients know they're talking to automation?", a: "They experience faster, more complete responses. Questions come from your firm's voice, and human conversation starts as soon as there is something worth talking about." },
      { q: "Does it replace our contact form?", a: "No — it feeds on whatever channels you already have. Forms, email, and referrals all flow into the same structured intake process." },
      { q: "How is this different from lead qualification?", a: "Intake covers existing inquiries becoming work-ready requests: completeness, categorization, routing. Lead qualification scores and prioritizes prospects against fit rules. Most firms use both." },
    ],
    seoTitle: "Client Intake Automation | Capture, Qualify, Route | SpielOS",
    seoDesc: "Client intake automation that captures inquiries, extracts requirements, collects documents, and routes qualified requests to the right person.",
  },
  {
    slug: "document-collection-automation",
    name: "Document Collection Automation",
    eyebrow: "DOCUMENT COLLECTION AUTOMATION",
    h1: "Collect every required document without chasing anyone.",
    heroCopy:
      "Engagements stall on paperwork. SpielOS generates the exact document list per client or matter, tracks what arrived, renames and files what comes in, reminds whoever owes what, and tells you precisely what is still missing — without a single manual chase.",
    manualSteps: [
      "Compile the document list from a template — again",
      "Send the request email",
      "Wait",
      "Receive six files named scan_final(3).pdf",
      "Figure out which requirement each file satisfies",
      "Notice one is expired and two are missing",
      "Chase — carefully, so the client doesn't feel nagged",
    ],
    painPoint:
      "Document collection is pure coordination: knowing what is needed, what arrived, what is wrong with it, and who to ask — repeatedly, for every client, until everything is in.",
    beforeText:
      "A spreadsheet (or memory) tracks the checklist, and someone spends hours a week matching attachments to requirements and writing reminder emails.",
    withText:
      "Requirements are generated per engagement, incoming files are classified and filed as they arrive, gaps are chased automatically, and status is always current — visible at a glance, not reconstructed on demand.",
    flowStates: ["List generated", "Requests sent", "Files arriving", "Classified & filed", "Validity checked", "Reminders sent", "Complete confirmed"],
    flowIcons: ["bx-list-check","bx-send","bx-download","bx-category","bx-check-square","bx-bell","bx-badge"],
    automateIntro: "What document collection automation does:",
    automate: [
      { title: "Generate required document lists", desc: "Per client type, matter, or engagement — not one generic checklist." },
      { title: "Request and track documents", desc: "Received vs. missing, per requirement, always current." },
      { title: "Send smart reminders", desc: "Only for what is actually missing, phrased kindly, stopped on arrival." },
      { title: "Classify incoming files", desc: "Figures out which requirement each attachment satisfies — even badly named ones." },
      { title: "Rename and file properly", desc: "Consistent naming into the right folder in your drive, automatically." },
      { title: "Check basic requirements", desc: "Dates, signatures, completeness — obvious problems caught early." },
      { title: "Request replacements", desc: "Expired or wrong documents trigger a specific, polite re-request." },
      { title: "Report true status", desc: "One glance shows what is in, what is missing, and what is blocked." },
    ],
    toolKeys: ["gmail", "google-drive", "slack", "notion"],
    audiences: [
      { name: "Accounting firms", note: "Seasonal floods of client documents with hard deadlines." },
      { name: "Recruitment agencies", note: "CVs, IDs, contracts, certifications per placement." },
      { name: "Legal & professional services", note: "Matter-specific checklists where completeness is non-negotiable." },
    ],
    relatedWorkflows: ["client-onboarding-automation", "follow-up-automation", "client-intake-automation"],
    relatedDepartments: ["analytics", "content"],
    boundaryIntro:
      "Nobody wants a robot nagging their clients. The automation chases politely, within your tone rules — and hands over the moment a conversation is better than a reminder.",
    runsAlone: [
      "Checklist generation, requesting, and receipt tracking",
      "Classification, renaming, and filing of arrivals",
      "Basic validity checks and replacement requests",
      "Status reporting across all engagements",
    ],
    stopsForHuman: [
      "Clients who are frustrated or delayed for personal reasons",
      "Documents needing professional judgment (legality, sufficiency)",
      "Exceptions like wrong-client or wrong-engagement submissions",
    ],
    faqs: [
      { q: "What is document collection automation?", a: "It is a workflow that generates the required document list per client, requests and tracks each item, classifies and files what arrives, and automatically reminds whoever owes what until everything is complete." },
      { q: "Can it handle badly named or scanned files?", a: "Yes. Classification looks at content, not filenames — scan_final(3).pdf gets identified, renamed, and filed to the right requirement." },
      { q: "Will it spam our clients with reminders?", a: "No. Cadence and tone follow rules you set, reminders reference the specific missing item, and chasing stops the moment the document arrives or a human takes over." },
      { q: "Where do collected documents end up?", a: "Filed in your own drive structure under consistent names — plus a live status view of received vs. missing across every engagement." },
    ],
    seoTitle: "Document Collection Automation | Stop Chasing Files | SpielOS",
    seoDesc: "Document collection automation: generate per-client checklists, classify and file arrivals, chase missing items politely, see true status instantly.",
  },
  {
    slug: "lead-qualification-automation",
    name: "Lead Qualification Automation",
    eyebrow: "LEAD QUALIFICATION AUTOMATION",
    h1: "Qualify every lead the minute it arrives — by your rules.",
    heroCopy:
      "Leads arrive faster than anyone can research them. SpielOS enriches each new lead, compares it against your qualification criteria, explains its classification, updates your CRM, and routes the promising ones onward — so hot leads get attention while they're hot.",
    manualSteps: [
      "Notice the new lead — eventually",
      "Google the company and the person",
      "Check them against fit criteria from memory",
      "Decide if they're worth a reply today",
      "Type research notes into the CRM",
      "Argue in the pipeline about which leads are real",
      "Find out the best lead of last month was never contacted",
    ],
    painPoint:
      "Qualification done from memory is inconsistent, and done slowly it is worthless. The leads that matter most are exactly the ones that won't wait.",
    beforeText:
      "Whichever lead someone gets to first gets researched; the rest age in the pipeline until someone has a spare hour that never comes.",
    withText:
      "Every lead gets the same treatment within minutes: enriched, scored against explicit criteria, classified with a stated reason, recorded, and routed — with humans making the decisions that deserve humans.",
    flowStates: ["Lead captured", "Enriched", "Criteria matched", "Scored & explained", "CRM updated", "Qualified routed", "Nurture set"],
    flowIcons: ["bx-user-plus","bx-search","bx-target-lock","bx-bar-chart-alt-2","bx-data","bx-send","bx-time-five"],
    automateIntro: "What lead qualification automation delivers:",
    automate: [
      { title: "Capture leads from every channel", desc: "Forms, inbound email, outbound replies — one pipeline." },
      { title: "Research company and person", desc: "Public signals gathered and summarized where it helps the decision." },
      { title: "Enrich existing information", desc: "Fill gaps in the record before scoring, not during the sales call." },
      { title: "Compare against your criteria", desc: "Explicit, editable qualification rules — not a black-box score." },
      { title: "Identify missing information", desc: "Flags what would change the classification and asks for it." },
      { title: "Score and categorize", desc: "Tiered, with the reason written out in plain language." },
      { title: "Update CRM and route", desc: "Qualified leads reach the right owner immediately, with context." },
      { title: "Trigger the right follow-up", desc: "Qualified gets outreach; nurture track gets patience; poor fit gets closure." },
    ],
    toolKeys: ["attio", "hubspot", "gmail", "telegram", "slack"],
    audiences: [
      { name: "B2B service businesses", note: "Fit depends on size, sector, and need — not gut feel." },
      { name: "Agencies with inbound", note: "Inquiry volume outruns manual research capacity." },
      { name: "Founders doing sales themselves", note: "Qualification happens at midnight or not at all." },
    ],
    relatedWorkflows: ["client-intake-automation", "follow-up-automation", "data-entry-automation"],
    relatedDepartments: ["marketing", "analytics"],
    boundaryIntro:
      "AI should explain, not decide your pipeline. Classification comes with reasons; irreversible choices — pursuing, pricing, discarding — stay with you.",
    runsAlone: [
      "Enrichment, criteria matching, and tiered classification",
      "Written explanations for every classification",
      "CRM updates and routing to owners",
      "Standard follow-up triggers per tier",
    ],
    stopsForHuman: [
      "Final pursuit decisions and pricing conversations",
      "Borderline fits where strategy matters more than rules",
      "Anything resembling an automated yes/no on a real relationship",
    ],
    faqs: [
      { q: "What is lead qualification automation?", a: "It enriches every incoming lead, compares it against your explicit qualification criteria, classifies it with a written explanation, updates your CRM, and routes qualified leads to the right owner immediately." },
      { q: "Will AI decide which leads we pursue?", a: "No. It classifies and explains; your team makes the pursue-or-pass decision. That boundary is deliberate — qualification informs judgment, it doesn't replace it." },
      { q: "Can we define our own criteria?", a: "Yes — criteria are explicit and editable: size, sector, need, geography, signal, whatever actually predicts fit in your business." },
      { q: "How fast does a new lead get qualified?", a: "Minutes, not days. The point is that hot leads get attention while they're still hot." },
    ],
    seoTitle: "Lead Qualification Automation | Score, Explain, Route | SpielOS",
    seoDesc: "Lead qualification automation that enriches every lead, scores it against your criteria with reasons, updates the CRM, and routes hot leads fast.",
  },
  {
    slug: "invoice-processing-automation",
    name: "Invoice Processing Automation",
    eyebrow: "INVOICE PROCESSING AUTOMATION",
    h1: "From invoice in the inbox to accounting-ready entry — without retyping.",
    heroCopy:
      "Supplier invoices arrive as PDFs and emails and become somebody's typing job. SpielOS receives them, extracts the fields, checks them for duplicates and consistency, prepares the accounting entry, and queues approval — with the original document and full history kept.",
    manualSteps: [
      "Download the attachment from email",
      "Read supplier, date, amounts, line items off the PDF",
      "Retype them into the accounting system",
      "Hunt through history to check it isn't a duplicate",
      "Match it to the right client, project, or cost center",
      "Chase approval from whoever owns the spend",
      "File the PDF somewhere findable — hopefully",
    ],
    painPoint:
      "Invoice processing is high-stakes typing: repetitive enough to breed carelessness, important enough that errors cost real money and credibility with accountants.",
    beforeText:
      "Each invoice is processed by hand end-to-end, with correctness depending on focus and duplicates depending on luck.",
    withText:
      "Invoices flow from inbox to accounting-ready draft automatically: fields extracted and validated, duplicates caught, matches proposed, approvals routed — and every entry traceable to its source document.",
    flowStates: ["Invoice received", "Fields extracted", "Checks passed", "Duplicates rejected", "Entry prepared", "Approval routed", "History archived"],
    flowIcons: ["bx-download","bx-search-alt","bx-check-square","bx-copy","bx-receipt","bx-user-check","bx-archive"],
    automateIntro: "What invoice processing automation covers:",
    automate: [
      { title: "Receive invoices from email", desc: "Attachments and forwarded bills captured into one processing pipeline." },
      { title: "Extract supplier and invoice fields", desc: "Vendor, dates, totals, VAT, line items — read from PDFs and scans." },
      { title: "Validate required information", desc: "Incomplete or malformed invoices flagged before they pollute accounting." },
      { title: "Detect duplicates", desc: "Cross-checked against history so nothing is booked or paid twice." },
      { title: "Match to existing records", desc: "Proposed links to purchase orders, clients, projects, or cost centers." },
      { title: "Prepare accounting entries", desc: "Drafts formatted for your accounting system — reviewed, then posted." },
      { title: "Route exceptions and approvals", desc: "Oddities go to the right reviewer; normal ones to routine approval." },
      { title: "Preserve documents and history", desc: "Original file plus every processing decision, permanently attached." },
    ],
    toolKeys: ["gmail", "google-drive", "slack", "notion"],
    audiences: [
      { name: "Small finance teams", note: "Bookkeeping capacity spent on typing, not reviewing." },
      { name: "Agencies & service firms", note: "Project-level cost tracking needs accurate invoice matching." },
      { name: "Businesses scaling past spreadsheets", note: "Volume broke the manual process months ago." },
    ],
    relatedWorkflows: ["data-entry-automation", "document-collection-automation", "follow-up-automation"],
    relatedDepartments: ["analytics"],
    boundaryIntro:
      "Money moves with approval, not automation. The system prepares everything and enforces the checkpoint — a human approves before anything posts.",
    runsAlone: [
      "Capture, extraction, validation, and duplicate detection",
      "Matching proposals and accounting-ready drafts",
      "Approval routing with full context attached",
      "Archiving originals with processing history",
    ],
    stopsForHuman: [
      "Every posting — approval is a human gate, always",
      "Mismatched amounts, unknown suppliers, and exceptions",
      "Payment execution, which stays entirely outside automation",
    ],
    faqs: [
      { q: "What is invoice processing automation?", a: "It reads incoming invoices, extracts and validates the fields, checks for duplicates, proposes matches, prepares the accounting entry, and routes it for approval — with the original document and full audit trail preserved." },
      { q: "Does AI approve payments automatically?", a: "No. Nothing posts or pays without a human approving it. Automation prepares and organizes; the financial checkpoint stays with your team." },
      { q: "Which accounting systems does it work with?", a: "Entries are prepared for your existing accounting workflow — your accountant or bookkeeper reviews and posts as usual, now from clean drafts instead of retyped numbers." },
      { q: "How are duplicate invoices detected?", a: "Each invoice is cross-checked against processing history on supplier, number, amount, and date. Suspected duplicates are held with both documents side by side." },
    ],
    seoTitle: "Invoice Processing Automation | Inbox to Accounting-Ready | SpielOS",
    seoDesc: "Invoice processing automation: extract fields, catch duplicates, match records, prepare accounting entries, route approvals — humans approve, always.",
  },
  {
    slug: "candidate-screening-automation",
    name: "Candidate Screening Automation",
    eyebrow: "CANDIDATE SCREENING AUTOMATION",
    h1: "Screen every applicant properly — before recruiters burn their day.",
    heroCopy:
      "Applications pile up faster than anyone can read them properly. SpielOS reads each CV, extracts the facts that matter, compares them against the role's explicit criteria, prepares honest candidate summaries, and ranks them for recruiter review — so human judgment starts from a shortlist, not an inbox.",
    manualSteps: [
      "Open application #47 of the day",
      "Skim the CV looking for the must-haves",
      "Try to remember what role this even was",
      "Copy basics into the ATS inconsistently",
      "Write rough notes you'll disagree with later",
      "Shortlist based on who you saw most recently",
      "Lose good candidates in the pile because fatigue won",
    ],
    painPoint:
      "Screening volume punishes thoroughness. Read every CV properly and you drown; skim and the best candidates vanish into the pile. Fatigue, not judgment, makes the cut.",
    beforeText:
      "Recruiters triage applications in stolen minutes between calls — and screening quality depends on what time of day it is.",
    withText:
      "Every application gets the same careful read: structured extraction, explicit-criteria comparison, a factual summary, and a ranking that explains itself. Recruiters spend their time judging shortlisted humans, not formatting chaos.",
    flowStates: ["Application in", "Facts extracted", "Criteria compared", "Summary prepared", "Ranked for review", "ATS updated", "Next steps triggered"],
    flowIcons: ["bx-envelope-open","bx-search-alt","bx-target-lock","bx-file","bx-bar-chart-alt-2","bx-data","bx-calendar"],
    automateIntro: "What candidate screening automation does:",
    automate: [
      { title: "Read applications and CVs", desc: "All formats — including the creative ones recruiters dread." },
      { title: "Extract structured profiles", desc: "Experience, skills, locations, rights to work, education — as clean data." },
      { title: "Compare against explicit criteria", desc: "The role's real must-haves and nice-to-haves, defined by the recruiter." },
      { title: "Retrieve relevant past candidates", desc: "Surfaces previous applicants who now fit a new role." },
      { title: "Prepare candidate summaries", desc: "Factual, comparable briefs: what they've done against what the role needs." },
      { title: "Rank for recruiter review", desc: "Ordered shortlists with reasoning — never an opaque score." },
      { title: "Update the ATS or CRM", desc: "Consistent records created for every applicant automatically." },
      { title: "Coordinate next steps", desc: "Interview scheduling and status follow-ups handled by the workflow." },
    ],
    toolKeys: ["gmail", "google-drive", "slack", "google-calendar", "notion"],
    audiences: [
      { name: "Recruitment agencies", note: "Screening volume is the business model's bottleneck." },
      { name: "Internal recruiting teams", note: "Roles open for weeks because review lags applications." },
      { name: "Staffing businesses", note: "Fast, consistent screening across many simultaneous roles." },
    ],
    relatedWorkflows: ["follow-up-automation", "data-entry-automation", "document-collection-automation"],
    relatedDepartments: ["marketing"],
    boundaryIntro:
      "Hiring decisions change lives, so they stay human — completely. The automation reads and organizes; recruiters evaluate, interview, and decide.",
    runsAlone: [
      "Reading, extraction, criteria comparison, and summarizing",
      "Ranking with transparent reasoning for review",
      "ATS record creation and status upkeep",
      "Screening-stage communication logistics",
    ],
    stopsForHuman: [
      "Every hiring decision, interview, and rejection",
      "Judgment about culture, potential, and fit beyond criteria",
      "Any candidate communication that carries good or bad news",
    ],
    faqs: [
      { q: "What is candidate screening automation?", a: "It reads every application, extracts structured candidate facts, compares them against the role's explicit criteria, prepares comparable summaries, and ranks them for recruiter review — so recruiters judge a shortlist instead of an inbox." },
      { q: "Does AI make hiring decisions?", a: "Never. It organizes and summarizes; recruiters make every decision. Ranking exists to direct attention, and its reasoning is always visible." },
      { q: "How is bias handled?", a: "Comparisons run only against the explicit, job-related criteria you define. Summaries are factual rather than evaluative, and humans review every recommendation before anything happens to a candidacy." },
      { q: "Does it work with our ATS?", a: "It creates and maintains consistent candidate records in the systems you use; deep ATS integrations are added where genuinely supported rather than claimed generically." },
    ],
    seoTitle: "Candidate Screening Automation | Shortlists, Not Piles | SpielOS",
    seoDesc: "Candidate screening automation: read every CV, compare against role criteria, prepare summaries, rank for recruiters. Hiring decisions stay human.",
  },
];

/** Hub groupings — organized by the actual work, not alphabetically. */
export const WORKFLOW_HUB_GROUPS: { label: string; blurb: string; slugs: string[] }[] = [
  { label: "Chasing", blurb: "Work that stalls because someone has to remember to ask.", slugs: ["follow-up-automation", "document-collection-automation"] },
  { label: "Moving information", blurb: "Copying, checking, and re-entering the same data.", slugs: ["data-entry-automation", "client-intake-automation", "invoice-processing-automation"] },
  { label: "Deciding & routing", blurb: "Sorting what arrived so the right person acts on it.", slugs: ["lead-qualification-automation", "candidate-screening-automation"] },
  { label: "Running processes", blurb: "Multi-step sequences that repeat for every client.", slugs: ["client-onboarding-automation"] },
];
