/**
 * Workflow solution pages — /solutions/workflows/[slug]/
 *
 * One search intent = one strong commercial page. Copy is written around the
 * actual operational workflow, never generated by swapping nouns in a shared
 * paragraph. Shared template lives at src/pages/solutions/workflows/[slug].astro.
 */

export interface WorkflowFaq { q: string; a: string }
export interface WorkflowAutomate { title: string; desc: string }

export interface WorkflowSolution {
  slug: string;
  name: string;
  eyebrow: string;
  h1: string;
  heroCopy: string;
  /** The concrete manual chain shown as a vertical step list. */
  manualSteps: string[];
  painPoint: string;
  beforeText: string;
  withText: string;
  /** Actual states/actions rendered as an arrow flow. */
  flowStates: string[];
  /** Matching boxicon per flow state. */
  flowIcons: string[];
  automateIntro: string;
  automate: WorkflowAutomate[];
  /** SOFTWARE_SOLUTIONS keys this workflow typically runs on. */
  toolKeys: string[];
  audiences: { name: string; note: string }[];
  /** Other workflow slugs to cross-link. */
  relatedWorkflows: string[];
  /** Department slugs under /solutions/ai-departments/. */
  relatedDepartments: string[];
  boundaryIntro: string;
  runsAlone: string[];
  stopsForHuman: string[];
  faqs: WorkflowFaq[];
  seoTitle: string;
  seoDesc: string;

  // ---- Persian variants (FA twins render these when present) ----
  nameFa?: string;
  h1Fa?: string;
  heroCopyFa?: string;
  manualStepsFa?: string[];
  painPointFa?: string;
  beforeTextFa?: string;
  withTextFa?: string;
  flowStatesFa?: string[];
  automateIntroFa?: string;
  automateFa?: WorkflowAutomate[];
  audiencesFa?: { name: string; note: string }[];
  boundaryIntroFa?: string;
  runsAloneFa?: string[];
  stopsForHumanFa?: string[];
  faqsFa?: WorkflowFaq[];
  seoTitleFa?: string;
  seoDescFa?: string;
}

export const WORKFLOW_SOLUTIONS: WorkflowSolution[] = [
  {
    slug: "client-onboarding-automation",
    name: "Client Onboarding Automation",
    eyebrow: "CLIENT ONBOARDING AUTOMATION",
    h1: "Automate client onboarding without managing every step.",
    heroCopy:
      "When a client signs, SpielOS can collect their information, request documents, create records, prepare your team, follow up on missing items, and keep the process moving — without someone manually working a checklist for every new client.",
    manualSteps: [
      "Contract signed → send welcome email by hand",
      "Write the same intake request again for each client",
      "Wait — then notice nothing arrived",
      "Chase missing information and documents",
      "Create folders, records, and project entries one by one",
      "Update the CRM so everyone else knows what happened",
      "Notify the team and schedule the kickoff",
    ],
    painPoint:
      "The problem isn't that any one step is difficult. Someone has to remember and coordinate all of them — for every single client, forever.",
    beforeText:
      "Someone checks what happened after signing, remembers the next step, sends the next message, and hopes nothing slips while they juggle other clients.",
    withText:
      "The workflow watches the onboarding state itself. It sends what should be sent, collects what should be collected, updates your systems, and brings you in only when a judgment call or exception needs a person.",
    flowStates: ["Contract signed", "Welcome sent", "Intake requested", "Documents tracked", "Records created", "Team notified", "Kickoff scheduled"],
    flowIcons: ["bx-check-square","bx-envelope","bx-task","bx-folder-open","bx-data","bx-bell","bx-calendar"],
    automateIntro: "What client onboarding automation handles end-to-end:",
    automate: [
      { title: "Send welcome and intake requests", desc: "Personalized to the client and engagement type the moment the deal is marked won." },
      { title: "Collect client information", desc: "Structured intake forms and email replies captured into clean fields." },
      { title: "Request required documents", desc: "The right document list per engagement, tracked received vs. outstanding." },
      { title: "Detect missing items", desc: "Knows exactly what is still open without anyone re-checking." },
      { title: "Follow up until complete", desc: "Polite, well-timed reminders that stop the moment the client responds." },
      { title: "Create CRM and project records", desc: "Folders, tasks, and database entries created consistently every time." },
      { title: "Prepare the team handoff", desc: "An internal summary of who the client is and what they need, ready before kickoff." },
      { title: "Escalate exceptions", desc: "Unusual answers, stalled clients, or special requests go to a person immediately." },
    ],
    toolKeys: ["gmail", "hubspot", "attio", "google-drive", "notion", "google-calendar"],
    audiences: [
      { name: "Agencies & consultancies", note: "Recurring onboarding per client, high coordination cost." },
      { name: "Accounting & professional services", note: "Document-heavy intake with strict completeness requirements." },
      { name: "Recruitment & staffing firms", note: "Client and placement onboarding running in parallel." },
    ],
    relatedWorkflows: ["document-collection-automation", "follow-up-automation", "data-entry-automation"],
    relatedDepartments: ["marketing", "content"],
    boundaryIntro:
      "Onboarding sets the tone of the whole relationship, so the boundary line matters. SpielOS automates the coordination and keeps the relationship with you.",
    runsAlone: [
      "Standard welcome and intake communications from approved templates",
      "Document tracking, reminders, and completeness checks",
      "Record, folder, and task creation across your systems",
      "Internal summaries and team notifications",
      "Kickoff scheduling against your calendar rules",
    ],
    stopsForHuman: [
      "Anything a client says that changes scope, price, or expectations",
      "Unusual document situations and exceptions",
      "The kickoff conversation itself",
    ],
    faqs: [
      { q: "What is client onboarding automation?", a: "It is a workflow that runs the administrative side of onboarding — welcome messages, information collection, document tracking, record creation, and team notification — automatically, instead of a person coordinating each step by hand." },
      { q: "Can AI follow up with clients automatically?", a: "Yes, within rules you approve. Follow-ups are sent on a sensible schedule, personalized to the engagement, and stop as soon as the client responds. Anything sensitive escalates to a human." },
      { q: "Can this work with our existing CRM and email?", a: "Yes. That is the default. SpielOS works on top of the CRM, email, drive, and messaging tools you already use rather than replacing them." },
      { q: "Does automated onboarding replace our account manager?", a: "No. It removes the checklist management so your account manager spends onboarding time talking to the client, not copying data and chasing documents." },
    ],
    seoTitle: "Client Onboarding Automation | SpielOS",
    seoDesc: "Automate client onboarding: welcome messages, intake, document collection, CRM records, and team handoff — run on the tools you already use.",
    nameFa: "اتوماسیون آنبوردینگ مشتری",
    h1Fa: "آنبوردینگ مشتری را بدون مدیریت قدم‌به‌قدم اتوماتیک کنید.",
    heroCopyFa: "وقتی مشتری امضا می‌کند، SpielOS می‌تواند اطلاعات را جمع کند، اسناد را درخواست کند، رکوردها را بسازد، تیم را آماده کند، موارد جاافتاده را پیگیری کند و پرونده را بدون یک نفرِ چک‌لیست‌دار جلو ببرد.",
    manualStepsFa: [
      "قرارداد امضا شد → ارسال ایمیل خوش‌آمد به‌صورت دستی",
      "نوشتن دوباره‌ی همان درخواست اطلاعات برای هر مشتری",
      "انتظار — بعد فهمیدن که هیچ‌چیز نرسیده",
      "پیگیری اطلاعات و اسناد جاافتاده",
      "ساخت پوشه، رکورد و پروژه یکی‌یکی",
      "به‌روزرسانی CRM تا بقیه خبردار شوند",
      "خبر کردن تیم و رزرو جلسه شروع",
    ],
    painPointFa: "مشکل این نیست که هیچ قدمی سخت است. مشکل این است که یک نفر باید همه‌شان را به یاد داشته باشد و هماهنگ کند — برای هر مشتری، برای همیشه.",
    beforeTextFa: "یک نفر بعد از امضای قرارداد چک می‌کند چه اتفاقی افتاده، قدم بعدی را از حفظ انجام می‌دهد، ایمیل بعدی را می‌فرستد و امیدوار است وسط کارهای دیگر چیزی جا نیفتد.",
    withTextFa: "ورک‌فلو خودش وضعیت آنبوردینگ را زیر نظر دارد. چیزی که باید فرستاده شود را می‌فرستد، چیزی که باید جمع شود را جمع می‌کند، سیستم‌ها را به‌روز نگه می‌دارد و فقط وقتی تصمیم انسانی لازم است شما را وارد می‌کند.",
    flowStatesFa: ["قرارداد امضا شد","خوش‌آمد ارسال شد","اطلاعات درخواست شد","اسناد ردیابی شد","رکوردها ساخته شد","تیم خبردار شد","جلسه رزرو شد"],
    automateIntroFa: "آنچه اتوماسیون آنبوردینگ سرتاسری انجام می‌دهد:",
    automateFa: [
      { title: "ارسال خوش‌آمد و درخواست اطلاعات", desc: "شخصی‌سازی‌شده برای مشتری و نوع همکاری، لحظه‌ای که معامله برده علامت می‌خورد." },
      { title: "جمع‌آوری اطلاعات مشتری", desc: "فرم‌ها و پاسخ ایمیال‌ها در فیلدهای تمیز و ساختاریافته ثبت می‌شود." },
      { title: "درخواست اسناد موردنیاز", desc: "لیست اسناد درست برای هر همکاری، با ردیابی رسیده و جاافتاده." },
      { title: "تشخیص موارد جاافتاده", desc: "بدون بررسی مجدد دستی، دقیقاً می‌داند چه چیزی باز است." },
      { title: "پیگیری تا تکمیل", desc: "یادآوری‌های مؤدبانه و زمان‌بندی‌شده که با اولین پاسخ متوقف می‌شوند." },
      { title: "ساخت رکورد CRM و پروژه", desc: "پوشه‌ها، تسک‌ها و رکوردها هر بار یکسان و کامل ساخته می‌شوند." },
      { title: "آماده‌سازی تحویل به تیم", desc: "خلاصه داخلی از اینکه مشتری کیست و چه می‌خواهد، قبل از جلسه آماده است." },
      { title: "ارجاع استثناها", desc: "پاسخ‌های غیرعادی، مشتری‌های متوقف یا درخواست‌های خاص فوراً به یک انسان می‌رسد." },
    ],
    audiencesFa: [
      { name: "آژانس‌ها و مشاوران", note: "آنبوردینگ تکرارشونده برای هر مشتری با هزینه هماهنگی بالا." },
      { name: "حسابداری و خدمات حرفه‌ای", note: "پذیرش پر از سند با الزامات کامل‌بودن سخت‌گیرانه." },
      { name: "شرکت‌های جذب و برون‌سپاری", note: "آنبوردینگ موازی مشتری و جایگاه‌های استخدامی." },
    ],
    boundaryIntroFa: "آنبوردینگ لحن کل رابطه را تعیین می‌کند، پس خط مرزی مهم است. SpielOS هماهنگی را اتوماتیک می‌کند و رابطه را برای شما نگه می‌دارد.",
    runsAloneFa: [
      "ارتباطات استاندارد خوش‌آمد و دریافت اطلاعات از روی قالب‌های تأییدشده",
      "ردیابی اسناد، یادآوری‌ها و بررسی کامل‌بودن",
      "ساخت رکورد، پوشه و تسک در سیستم‌های شما",
      "خلاصه‌های داخلی و اطلاع‌رسانی به تیم",
      "رزرو جلسه شروع بر اساس قوانین تقویم شما",
    ],
    stopsForHumanFa: [
      "هر چیزی که مشتری درباره محدوده، قیمت یا انتظارات می‌گوید",
      "موقعیت‌های خاص و استثناهای سند",
      "خودِ مکالمه جلسه شروع",
    ],
    faqsFa: [
      { q: "اتوماسیون آنبوردینگ مشتری چیست؟", a: "ورک‌فلویی است که بخش اداری آنبوردینگ — پیام خوش‌آمد، جمع‌آوری اطلاعات، ردیابی اسناد، ساخت رکورد و اطلاع‌رسانی به تیم — را بدون هماهنگی دستی اجرا می‌کند." },
      { q: "آیا هوش مصنوعی می‌تواند به‌طور خودکار با مشتری پیگیری کند؟", a: "بله، داخل قوانینی که شما تأیید می‌کنید. پیگیری‌ها زمان‌بندی منطقی دارند، شخصی‌سازی شده‌اند و با اولین پاسخ متوقف می‌شوند. موضوعات حساس به انسان ارجاع می‌شود." },
      { q: "با CRM و ایمیل فعلی ما کار می‌کند؟", a: "بله، این حالت پیش‌فرض است. SpielOS روی CRM، ایمیل، درایو و ابزارهای پیام فعلی شما اجرا می‌شود؛ جایگزین‌شان نمی‌شود." },
      { q: "آیا آنبوردینگ اتوماتیک جانشین اکانت منیجر ما می‌شود؟", a: "نه. فقط مدیریت چک‌لیست را حذف می‌کند تا وقت اکانت منیجر صرف گفتگو با مشتری شود، نه کپی داده و دویدن دنبال سند." },
    ],
    seoTitleFa: "اتوماسیون آنبوردینگ مشتری | SpielOS",
    seoDescFa: "اتوماسیون آنبوردینگ مشتری: خوش‌آمد، دریافت اطلاعات، جمع‌آوری اسناد، رکورد CRM و تحویل به تیم — روی ابزارهایی که همین حالا دارید.",
  },
  {
    slug: "data-entry-automation",
    name: "Data Entry Automation",
    eyebrow: "DATA ENTRY AUTOMATION",
    h1: "Stop moving the same data between systems by hand.",
    heroCopy:
      "Every email, form, PDF, and spreadsheet that arrives still ends up retyped into your CRM, database, or accounting tool. SpielOS reads incoming information, extracts the right fields, validates them, and puts them where they belong — with the source kept for checking.",
    manualSteps: [
      "Open the email, form response, or attachment",
      "Read it and find the fields that matter",
      "Switch to the CRM, sheet, or system",
      "Retype the values — hoping nothing is mistyped",
      "Notice a duplicate or contradiction halfway through",
      "Fix the format someone else will complain about later",
      "Repeat dozens of times a day",
    ],
    painPoint:
      "No individual entry is hard. But the volume compounds: retyping is slow, error-prone, invisible in cost reports, and it is the work nobody was hired to do.",
    beforeText:
      "A person is the copy-paste layer between your inbox and your systems — and the quality control layer too, usually at the same time.",
    withText:
      "Incoming information is read, structured, validated, and written to the right system automatically. Uncertain entries are flagged for review instead of silently guessed, and every value keeps a link back to its source.",
    flowStates: ["Item arrives", "Fields extracted", "Data validated", "Duplicates checked", "Systems updated", "Uncertain flagged", "Source archived"],
    flowIcons: ["bx-download","bx-search-alt","bx-check-square","bx-copy","bx-data","bx-error","bx-archive"],
    automateIntro: "What data entry automation takes off your team:",
    automate: [
      { title: "Read emails, forms, and documents", desc: "Invoices, intake forms, applications, order confirmations — structured or messy." },
      { title: "Extract relevant fields", desc: "Names, amounts, dates, IDs, addresses — mapped to your schema." },
      { title: "Validate required data", desc: "Missing or malformed values are caught before they enter your systems." },
      { title: "Normalize formats", desc: "Dates, phone numbers, currencies, and naming conventions standardized on the way in." },
      { title: "Detect duplicates", desc: "Cross-checks existing records so the same lead or invoice is not entered twice." },
      { title: "Update CRM, sheets, and databases", desc: "Written directly to the systems you already use, in the fields you already have." },
      { title: "Flag uncertain entries", desc: "Low-confidence extractions queue for quick human review instead of corrupting data." },
      { title: "Preserve source evidence", desc: "Every stored value links back to the original email or document it came from." },
    ],
    toolKeys: ["gmail", "attio", "hubspot", "notion", "google-drive", "zapier"],
    audiences: [
      { name: "Operations teams", note: "High volume of forms, orders, and confirmations daily." },
      { name: "Sales & CRM owners", note: "Lead and contact data arriving from many channels." },
      { name: "Finance & back office", note: "Invoices and statements that must land in accounting correctly." },
    ],
    relatedWorkflows: ["invoice-processing-automation", "lead-qualification-automation", "client-intake-automation"],
    relatedDepartments: ["analytics", "seo"],
    boundaryIntro:
      "Bad data is more expensive than slow data. So the automation writes confidently only when it is confident — and asks otherwise.",
    runsAlone: [
      "Extraction and normalization of standard, recurring formats",
      "Duplicate checks and cross-references against existing records",
      "Direct writes for high-confidence matches",
      "Archiving source documents with every entry",
    ],
    stopsForHuman: [
      "Ambiguous or low-confidence values — queued for review, never guessed",
      "Conflicting records that need a business decision",
      "New document types until the pattern is taught once",
    ],
    faqs: [
      { q: "What is data entry automation?", a: "It is software that reads incoming emails, forms, and documents, extracts the relevant fields, validates them, and writes them into your CRM, spreadsheets, or databases automatically — keeping the source linked to every value." },
      { q: "Will AI make mistakes entering our data?", a: "It can — which is why uncertain extractions are flagged for a quick human check instead of being written blindly. High-confidence standard formats are entered directly; anything ambiguous waits for review." },
      { q: "Do we need to change our CRM or tools?", a: "No. The automation writes into the systems you already use. Migration is not part of the offer." },
      { q: "How is this different from Zapier?", a: "Zapier moves data between defined triggers and fields. Data entry automation reads unstructured input — emails, PDFs, scans — decides what matters, validates it, and handles the exceptions that break rigid zaps." },
    ],
    seoTitle: "Data Entry Automation | Stop Retyping Between Systems | SpielOS",
    seoDesc: "Data entry automation that reads emails, forms, and documents, extracts and validates fields, and updates your CRM and systems — sources preserved.",
    nameFa: "اتوماسیون ورود داده",
    h1Fa: "دیگر داده‌ها را بین سیستم‌ها با دست جابه‌جا نکنید.",
    heroCopyFa: "هر ایمیل، فرم و PDF که می‌رسد هنوز کار تایپ دوباره است. SpielOS اطلاعات ورودی را می‌خواند، فیلدهای مهم را استخراج و اعتبارسنجی می‌کند و سر جای درست می‌نویسد — همراه با نگه‌داشتن منبع برای راستی‌آزمایی.",
    manualStepsFa: [
      "باز کردن ایمیل، پاسخ فرم یا پیوست",
      "خواندن و پیدا کردن فیلدهای مهم",
      "سوییچ به CRM، شیت یا سیستم دیگر",
      "تایپ دوباره مقادیر — با امید به اینکه اشتباه تایپی نباشد",
      "وسط کار، پیدا کردن رکورد تکراری یا متناقض",
      "درست کردن قالبی که بعداً کسی به آن گیر می‌دهد",
      "تکرار همه‌ی این‌ها ده‌ها بار در روز",
    ],
    painPointFa: "هیچ ثبتِ واحدی سخت نیست. اما حجم جمع می‌شود: تایپ دوباره کند است، خطا دارد، در گزارش هزینه‌ها نامرئی است و کسی برایش استخدام نشده بود.",
    beforeTextFa: "یک انسان لایه‌ی کپی‌پیست بین ایمیل و سیستم‌های شماست — و معمولاً هم‌زمان لایه‌ی کنترل کیفیت.",
    withTextFa: "اطلاعات ورودی خوانده، ساختارمند، اعتبارسنجی و خودکار در سیستم درست نوشته می‌شود. موارد مبهم به‌جای حدس زدن، برای بازبینی علامت می‌خورند و هر مقدار به منبع اصلی‌اش لینک می‌ماند.",
    flowStatesFa: ["مورد رسید","فیلدها استخراج شد","داده اعتبارسنجی شد","تکراری بررسی شد","سیستم‌ها به‌روز شد","مبهم علامت خورد","منبع بایگانی شد"],
    automateIntroFa: "آنچه اتوماسیون ورود داده از دوش تیم برمی‌دارد:",
    automateFa: [
      { title: "خواندن ایمیل، فرم و سند", desc: "فاکتور، فرم پذیرش، رزومه و تأییدیه سفارش — ساختاریافته یا به‌هم‌ریخته." },
      { title: "استخراج فیلدهای مرتبط", desc: "نام، مبلغ، تاریخ، شناسه — نگاشت‌شده به اسکیمای شما." },
      { title: "اعتبارسنجی داده الزامی", desc: "مقادیر ناقص یا غلط قبل از ورود به سیستم‌ها گرفته می‌شوند." },
      { title: "استانداردسازی قالب", desc: "تاریخ، شماره تماس، ارز و نام‌گذاری یکسان‌سازی می‌شوند." },
      { title: "تشخیص تکراری‌ها", desc: "با رکوردهای موجود چک می‌شود تا لید یا فاکتور دو بار ثبت نشود." },
      { title: "به‌روزرسانی CRM، شیت و دیتابیس", desc: "مستقیم در همان سیستم‌ها و همان فیلدهای فعلی نوشته می‌شود." },
      { title: "علامت‌گذاری موارد مبهم", desc: "استخراج‌های کم‌اعتماد برای بازبینی سریع انسانی صف می‌شوند، نه حدس زدن بی‌صدا." },
      { title: "حفظ منبع", desc: "هر مقدار ذخیره‌شده به ایمیل یا سند اصلی‌اش لینک دارد." },
    ],
    audiencesFa: [
      { name: "تیم‌های عملیات", note: "حجم روزانه بالای فرم، سفارش و تأییدیه." },
      { name: "مالکان CRM و فروش", note: "داده لید و مخاطب از کانال‌های مختلف می‌رسد." },
      { name: "مالی و پشتیبان", note: "فاکتور و صورت‌حسابی که باید درست وارد حسابداری شود." },
    ],
    boundaryIntroFa: "داده‌ی خراب از داده‌ی کند گران‌تر تمام می‌شود. پس اتوماسیون فقط وقتی مطمئن است با اطمینان می‌نویسد — وگرنه می‌پرسد.",
    runsAloneFa: [
      "استخراج و استانداردسازی فرمت‌های تکراری و استاندارد",
      "بررسی تکراری‌ها و تطبیق با رکوردهای موجود",
      "نوشتن مستقیم برای تطابق‌های پراعتماد",
      "بایگانی سند منبع همراه هر ثبت",
    ],
    stopsForHumanFa: [
      "مقادیر مبهم یا کم‌اعتماد — برای بازبینی صف می‌شود، هرگز حدس زده نمی‌شود",
      "رکوردهای متناقض که تصمیم کسب‌وکاری می‌خواهند",
      "نوع جدید اسناد تا وقتی الگویش یک بار آموزش داده شود",
    ],
    faqsFa: [
      { q: "اتوماسیون ورود داده چیست؟", a: "نرم‌افزاری است که ایمیل‌ها، فرم‌ها و اسناد ورودی را می‌خواند، فیلدهای مرتبط را استخراج و اعتبارسنجی می‌کند و در CRM، شیت یا دیتابیس شما می‌نویسد — با لینک منبع برای هر مقدار." },
      { q: "آیا هوش مصنوعی در ثبت داده اشتباه می‌کند؟", a: "می‌تواند — برای همین استخراج‌های کم‌اعتماد بدون نوشته‌شدن، برای بازبینی سریع انسانی علامت می‌خورند. فرمت‌های استاندارد پراعتماد مستقیم ثبت می‌شوند؛ هر چیز مبهم منتظر بررسی می‌ماند." },
      { q: "باید CRM یا ابزارهایمان را عوض کنیم؟", a: "نه. اتوماسیون در همین سیستم‌های فعلی می‌نویسد. مهاجرت اصلاً بخشی از پیشنهاد نیست." },
      { q: "فرقش با Zapier چیست؟", a: "Zapier داده را بین تریگرها و فیلدهای تعریف‌شده جابه‌جا می‌کند. اتوماسیون ورود داده ورودی غیرساختاریافته — ایمیل، PDF، اسکن — را می‌خواند، تشخیص می‌دهد چه مهم است، اعتبارسنجی می‌کند و استثناها را مدیریت می‌کند که Zapهای سخت‌گیرانه را می‌شکنند." },
    ],
    seoTitleFa: "اتوماسیون ورود داده | پایان تایپ دوباره | SpielOS",
    seoDescFa: "اتوماسیون ورود داده که ایمیل، فرم و سند را می‌خواند، فیلدها را استخراج و اعتبارسنجی می‌کند و CRM شما را به‌روز نگه می‌دارد — با حفظ منبع.",
  },
  {
    slug: "follow-up-automation",
    name: "Follow-Up Automation",
    eyebrow: "FOLLOW-UP AUTOMATION",
    h1: "Never lose a thread because someone forgot to follow up.",
    heroCopy:
      "Leads, clients, documents, quotes, approvals — something is always waiting on a reply. SpielOS tracks what is actually outstanding, sends the right follow-up at the right time, stops the moment someone responds, and escalates the cases that need a person.",
    manualSteps: [
      "Remember (or forget) who was supposed to reply",
      "Check the thread to see what was already said",
      "Draft yet another nudge — politely, again",
      "Guess how long to wait before sending it",
      "Discover the deal died because nobody followed up twice",
      "Apologize to the client whose document request slipped",
      "Keep a mental list of everything still open",
    ],
    painPoint:
      "Follow-up is memory work. It dies quietly whenever people get busy — and the cost shows up weeks later as stalled deals, late projects, and awkward apologies.",
    beforeText:
      "Follow-ups live in inboxes, notes, and someone's head. Whether they happen depends on who is busiest that week.",
    withText:
      "Outstanding items are tracked as workflow state. The system knows what was asked, when, and whether a response arrived — and follows up accordingly, updating records and escalating what goes cold.",
    flowStates: ["Request sent", "Waiting tracked", "Response watched", "Reminder timed", "Thread resumed", "Status updated", "Overdue escalated"],
    flowIcons: ["bx-send","bx-time-five","bx-show","bx-bell","bx-comment-detail","bx-refresh","bx-error"],
    automateIntro: "What follow-up automation covers:",
    automate: [
      { title: "Detect what is outstanding", desc: "Leads, client replies, documents, quote approvals, internal sign-offs — tracked as state, not memory." },
      { title: "Understand current context", desc: "Reads the thread so the follow-up continues the conversation instead of restarting it." },
      { title: "Send appropriate follow-ups", desc: "Right tone, right channel, referencing what was actually requested." },
      { title: "Stop when someone responds", desc: "The moment a reply lands, reminders stop and the workflow moves forward." },
      { title: "Adapt timing to state", desc: "Hot lead vs. overdue invoice get different cadences, defined by your rules." },
      { title: "Update CRM and task status", desc: "Every touch recorded so the pipeline reflects reality." },
      { title: "Escalate overdue or unusual cases", desc: "Stalled or sensitive threads surface to a person with full context attached." },
    ],
    toolKeys: ["gmail", "slack", "hubspot", "attio", "telegram", "whatsapp"],
    audiences: [
      { name: "Sales teams", note: "Pipeline leaks happen between touches, not during them." },
      { name: "Agencies & service firms", note: "Client-side dependencies stall delivery constantly." },
      { name: "Recruitment firms", note: "Candidates, clients, and document chases all in parallel." },
    ],
    relatedWorkflows: ["client-onboarding-automation", "document-collection-automation", "lead-qualification-automation"],
    relatedDepartments: ["marketing", "content"],
    boundaryIntro:
      "A bad follow-up costs more than a missed one. Tone rules and escalation lines are yours to define — and the machine stays inside them.",
    runsAlone: [
      "Routine nudges for documents, approvals, and unanswered requests",
      "State-based cadences you define per case type",
      "CRM and task updates after every touch",
      "Stopping instantly when a human conversation begins",
    ],
    stopsForHuman: [
      "Sensitive conversations — complaints, negotiations, bad news",
      "Any thread where the reply changes terms or expectations",
      "Escalations after a case goes quiet too long",
    ],
    faqs: [
      { q: "What does follow-up automation do?", a: "It tracks everything waiting on a response — leads, clients, documents, approvals — and sends appropriate reminders until resolved, stopping automatically when someone replies." },
      { q: "Will automated follow-ups sound robotic?", a: "They are drafted from your templates and the actual thread context, so they reference the real request. You approve tone rules up front, and anything sensitive routes to a person." },
      { q: "Does it cover leads, clients, and internal follow-ups?", a: "Yes — lead, client, document, quote, and internal approval follow-ups all run on the same state-tracking engine with different rules per type." },
      { q: "How does it know when to stop following up?", a: "When a response arrives, when you mark the case handled, or when your escalation rule says a person should take over." },
    ],
    seoTitle: "Follow-Up Automation | Leads, Clients & Documents | SpielOS",
    seoDesc: "Follow-up automation that tracks every outstanding reply — leads, clients, documents, approvals — and follows up until it's done. No thread forgotten.",
    nameFa: "اتوماسیون پیگیری",
    h1Fa: "هیچ مکالمه‌ای به‌خاطر فراموشیِ پیگیری از دست نرود.",
    heroCopyFa: "لید، مشتری، سند، پیش‌فاکتور، تأییدیه — همیشه چیزی در انتظار پاسخ است. SpielOS ردیابی می‌کند چه چیزی واقعاً باز است، پیگیری درست را سر وقت می‌فرستد، با اولین پاسخ متوقف می‌شود و موارد نیازمند انسان را ارجاع می‌دهد.",
    manualStepsFa: [
      "یادآوری (یا فراموشی) اینکه کی قرار بود جواب بدهد",
      "مرور مکالمه برای فهمیدن چه گفته بودیم",
      "نوشتن دوباره‌ی یک یادآوری مؤدبانه — برای بار سوم",
      "حدس زدن چقدر صبر کنیم قبل از ارسال",
      "فهمیدن اینکه معامله مرده چون کسی دوباره پیگیری نکرد",
      "عذرخواهی از مشتری‌ای که درخواست سندش گم شد",
      "نگه داشتن لیست ذهنی همه‌ی کارهای باز",
    ],
    painPointFa: "پیگیری کارِ حافظه است. هر وقت آدم‌ها شلوغ می‌شوند بی‌صدا می‌میرد — و هزینه‌اش هفته‌ها بعد به‌شکل معامله‌های متوقف و پروژه‌های دیرکردار ظاهر می‌شود.",
    beforeTextFa: "پیگیری‌ها توی ایمیل‌ها، یادداشت‌ها و ذهن یک نفر زندگی می‌کنند. اتفاق افتادنشان به این بستگی دارد که آن هفته کی busiest بوده.",
    withTextFa: "موارد در انتظار به‌شکل وضعیتِ ورک‌فلو ردیابی می‌شوند. سیستم می‌داند چه خواسته شده، کِی، و آیا پاسخی رسیده — و بر همان اساس پیگیری می‌کند، رکوردها را به‌روز نگه می‌دارد و موارد سردشده را ارجاع می‌دهد.",
    flowStatesFa: ["درخواست ارسال شد","انتظار ردیابی شد","پاسخ زیر نظر بود","یادآوری زمان‌بندی شد","مکالمه ادامه یافت","وضعیت به‌روز شد","دیرکرد ارجاع شد"],
    automateIntroFa: "آنچه اتوماسیون پیگیری پوشش می‌دهد:",
    automateFa: [
      { title: "تشخیص موارد در انتظار", desc: "لید، پاسخ مشتری، اسناد، تأیید پیش‌فاکتور و تأیید داخلی — به‌شکل وضعیت، نه حافظه." },
      { title: "درک بافت فعلی", desc: "مکالمه را می‌خواند تا پیگیری ادامه‌ی همان گفتگو باشد، نه شروع دوباره." },
      { title: "ارسال پیگیری مناسب", desc: "لحن و کانال درست، اشاره به همان درخواست واقعی." },
      { title: "توقف با اولین پاسخ", desc: "هر لحظه پاسخ برسد، یادآوری‌ها قطع و ورک‌فلو جلو می‌رود." },
      { title: "زمان‌بندی بر اساس وضعیت", desc: "لید داغ و فاکتور سرسیدشده ریتم‌های متفاوتی دارند که شما تعریف می‌کنید." },
      { title: "به‌روزرسانی CRM و تسک", desc: "هر تماس ثبت می‌شود تا پایپ‌لاین واقعیت را نشان دهد." },
      { title: "ارجاع دیرکردها و موارد غیرعادی", desc: "مکالمات متوقف یا حساس با کل بافت به یک انسان می‌رسد." },
    ],
    audiencesFa: [
      { name: "تیم‌های فروش", note: "نشت پایپ‌لاین بین تماس‌ها اتفاق می‌افتد، نه داخل آن‌ها." },
      { name: "آژانس‌ها و شرکت‌های خدماتی", note: "وابستگی به مشتری تحویل را مدام متوقف می‌کند." },
      { name: "شرکت‌های جذب نیرو", note: "کاندید، مشتری و تعقیب سند همه موازی‌اند." },
    ],
    boundaryIntroFa: "یک پیگیری بد از یک پیگیری جامانده گران‌تر تمام می‌شود. قوانین لحن و خط قرمزهای ارجاع را شما تعریف می‌کنید — و ماشین داخل همان می‌ماند.",
    runsAloneFa: [
      "یادآوری‌های معمول برای اسناد، تأییدیه‌ها و درخواست‌های بی‌پاسخ",
      "ریتم‌های وضعیت‌محور که خودتان برای هر نوع پرونده تعریف می‌کنید",
      "به‌روزرسانی CRM و تسک بعد از هر تماس",
      "توقف فوری وقتی گفتگوی انسانی شروع می‌شود",
    ],
    stopsForHumanFa: [
      "مکالمات حساس — شکایت، مذاکره، خبر بد",
      "هر رشته‌ای که پاسخش شرط‌ها یا انتظارات را عوض می‌کند",
      "ارجاع بعد از سکوت طولانی یک پرونده",
    ],
    faqsFa: [
      { q: "اتوماسیون پیگیری چه کاری می‌کند؟", a: "همه‌ی موارد در انتظار پاسخ — لید، مشتری، سند، تأییدیه — را ردیابی می‌کند و تا حل‌شدن پیگیری می‌فرستد؛ با رسیدن پاسخ خودکار متوقف می‌شود." },
      { q: "پیگیری‌های اتوماتیک رباتیک به نظر نمی‌رسند؟", a: "از روی قالب‌های شما و بافت واقعی مکالمه نوشته می‌شوند و به درخواست واقعی ارجاع می‌دهند. لحن را از قبل تأیید می‌کنید و موارد حساس به انسان می‌رود." },
      { q: "لید، مشتری و پیگیری داخلی را هم پوشش می‌دهد؟", a: "بله — پیگیری لید، مشتری، سند، پیش‌فاکتور و تأییدیه داخلی روی یک موتور وضعیت‌محور با قوانین متفاوت برای هر نوع اجرا می‌شود." },
      { q: "از کجا بفهمد دیگر پیگیری نکند؟", a: "وقتی پاسخ برسد، وقتی شما پرونده را بسته علامت بزنید، یا وقتی قانون ارجاع بگوید یک انسان باید接管 کند." },
    ],
    seoTitleFa: "اتوماسیون پیگیری | لید، مشتری و سند | SpielOS",
    seoDescFa: "اتوماسیون پیگیری که هر پاسخ در انتظار را ردیابی می‌کند — لید، مشتری، سند و تأییدیه — تا انجام شدن پیگیری می‌کند. هیچ رشته‌ای فراموش نمی‌شود.",
  },
  {
    slug: "client-intake-automation",
    name: "Client Intake Automation",
    eyebrow: "CLIENT INTAKE AUTOMATION",
    h1: "Turn incoming inquiries into qualified, routed, ready-to-work requests.",
    heroCopy:
      "New requests arrive by form, email, and referral — half-finished and unstructured. SpielOS captures them, extracts what is actually being asked, asks the missing questions, files everything in your CRM, and routes it to the right person with a summary already written.",
    manualSteps: [
      "Notice the inquiry arrived in three places at once",
      "Read it and figure out what they actually need",
      "Email back asking the questions they forgot to answer",
      "Copy details into the CRM imperfectly",
      "Decide who should handle it — from memory",
      "Brief that person manually",
      "Lose track of the ones that never got a reply",
    ],
    painPoint:
      "Intake is where work enters your company — and it is usually the least engineered process in it. Slow or sloppy intake loses clients before the work even starts.",
    beforeText:
      "Whoever sees the inquiry first becomes the intake process: reading, replying, filing, routing, and remembering to circle back.",
    withText:
      "Every inquiry is captured the same way: structured, completed, categorized, filed, and routed with an internal summary — so the first human conversation happens with context already prepared.",
    flowStates: ["Inquiry arrives", "Requirements extracted", "Gaps asked", "Docs collected", "Categorized", "Routed to owner", "Summary ready"],
    flowIcons: ["bx-envelope-open","bx-search-alt","bx-help-circle","bx-folder-open","bx-collection","bx-network-chart","bx-file"],
    toolKeys: ["gmail", "hubspot", "attio", "notion", "slack"],
        automateIntro: "What client intake automation handles:",
    automate: [
      { title: "Capture inquiries from any channel", desc: "Forms, forwarded emails, referrals — one consistent intake pipeline." },
      { title: "Extract structured requirements", desc: "What they need, when, budget signals, constraints — pulled out of free text." },
      { title: "Ask the missing questions", desc: "Targeted follow-ups that complete the picture without embarrassing reply chains." },
      { title: "Collect relevant documents", desc: "The right files requested and tracked from day one." },
      { title: "Qualify or categorize requests", desc: "Sorted against your criteria: fit, urgency, service type." },
      { title: "Create and update CRM records", desc: "Clean records created automatically — no transcription step." },
      { title: "Route to the correct person", desc: "By service line, workload, or rule — not by whoever noticed first." },
      { title: "Prepare the internal summary", desc: "Who they are, what they need, what is still open — before the first call." },
    ],
    audiences: [
      { name: "Professional services firms", note: "Every engagement starts with an unstructured inquiry." },
      { name: "Agencies", note: "Mixed inbound: retainers, projects, one-off requests." },
      { name: "Accounting & legal practices", note: "Compliance-sensitive intake that must be complete." },
    ],
    relatedWorkflows: ["lead-qualification-automation", "client-onboarding-automation", "document-collection-automation"],
    relatedDepartments: ["marketing", "analytics"],
    boundaryIntro:
      "First impressions decide whether inquiries become clients. Intake automation handles the paperwork around that first impression — you keep the conversation.",
    runsAlone: [
      "Capturing, structuring, and completing inquiry information",
      "Document requests and tracking",
      "CRM creation and routing by your rules",
      "Internal briefs prepared before anyone picks up the phone",
    ],
    stopsForHuman: [
      "The first real conversation with the prospective client",
      "Fit judgments your rules cannot express",
      "Red-flag situations that need a partner's eye",
    ],
    faqs: [
      { q: "What is client intake automation?", a: "It is a workflow that captures every incoming inquiry, extracts the actual requirement, completes missing information, files it in your CRM, and routes it to the right person with a prepared summary." },
      { q: "Will clients know they're talking to automation?", a: "They experience faster, more complete responses. Questions come from your firm's voice, and human conversation starts as soon as there is something worth talking about." },
      { q: "Does it replace our contact form?", a: "No — it feeds on whatever channels you already have. Forms, email, and referrals all flow into the same structured intake process." },
      { q: "How is this different from lead qualification?", a: "Intake covers existing inquiries becoming work-ready requests: completeness, categorization, routing. Lead qualification scores and prioritizes prospects against fit rules. Most firms use both." },
    ],
    seoTitle: "Client Intake Automation | Capture, Qualify, Route | SpielOS",
    seoDesc: "Client intake automation that captures inquiries, extracts requirements, collects documents, and routes qualified requests to the right person.",
    nameFa: "اتوماسیون پذیرش مشتری",
    h1Fa: "درخواست‌های ورودی را به درخواست‌های صلاحیت‌دار، مسیریابی‌شده و آماده‌ی کار تبدیل کنید.",
    heroCopyFa: "درخواست‌های جدید از فرم، ایمیل و معرفی می‌رسند — نصفه و نامنظم. SpielOS ثبت‌شان می‌کند، از متن آزاد استخراج می‌کند چه خواسته شده، سؤال‌های جامانده را می‌پرسد، همه را در CRM فایل می‌کند و با خلاصه‌ای آماده به فرد درست ارجاع می‌دهد.",
    manualStepsFa: [
      "متوجه شدن که درخواست هم‌زمان در سه جا رسیده",
      "خواندن و حدس زدن واقعاً چه می‌خواهند",
      "ایمیل برگشت برای سؤال‌هایی که جواب نداده بودند",
      "کپی کردن جزئیات به CRM — ناقص",
      "تصمیم از حافظه اینکه کی باید رسیدگی کند",
      "بریف کردن دستی آن فرد",
      "گم شدن درخواست‌هایی که هیچ‌وقت جواب نگرفتند",
    ],
    painPointFa: "پذیرش همان‌جایی است که کار وارد شرکت شما می‌شود — و معمولاً کمترین مهندسی‌شده‌ترین فرایند آن است. پذیرشِ کند یا شلخته مشتری را قبل از شروع کار از دست می‌دهد.",
    beforeTextFa: "هر کس اول درخواست را ببیند، خودش می‌شود فرایند پذیرش: خواندن، جواب دادن، فایل کردن، مسیریابی و یادآوری برای برگشتن.",
    withTextFa: "هر درخواست یکسان گرفته می‌شود: ساختارمند، کامل، دسته‌بندی‌شده، فایل‌شده و با خلاصه داخلی مسیریابی‌شده — تا اولین گفتگوی انسانی با بافت آماده شروع شود.",
    flowStatesFa: ["درخواست رسید","الزامات استخراج شد","خلأها پرسیده شد","اسناد جمع شد","دسته‌بندی شد","به مالک ارجاع شد","خلاصه آماده شد"],
    automateIntroFa: "آنچه اتوماسیون پذیرش مشتری انجام می‌دهد:",
    automateFa: [
      { title: "ثبت درخواست از هر کانالی", desc: "فرم، ایمیل فورواردي، معرفی — یک خط لوله یکسان." },
      { title: "استخراج الزامات ساختاریافته", desc: "چه می‌خواهند، کِی، نشانه‌های بودجه و محدودیت‌ها — از دل متن آزاد." },
      { title: "پرسیدن سؤال‌های جامانده", desc: "پیگیری هدفمند که تصویر را کامل می‌کند بدون رشته ایمیل‌های خسته‌کننده." },
      { title: "جمع‌آوری اسناد مرتبط", desc: "فایل‌های درست از روز اول درخواست و ردیابی می‌شوند." },
      { title: "صلاحیت‌سنجی یا دسته‌بندی", desc: "بر اساس معیارهای شما: تناسب، فوریت، نوع خدمت." },
      { title: "ساخت و به‌روزرسانی رکورد CRM", desc: "رکورد تمیز خودکار ساخته می‌شود — بدون مرحله تایپ مجدد." },
      { title: "ارجاع به فرد درست", desc: "بر اساس خط خدمت، ظرفیت یا قانون — نه بر اساس هر کس اول دید." },
      { title: "آماده‌سازی خلاصه داخلی", desc: "کیست، چه می‌خواهد، چه باز مانده — قبل از اولین تماس." },
    ],
    audiencesFa: [
      { name: "شرکت‌های خدمات حرفه‌ای", note: "هر قرارداد با یک درخواست غیرساختاریافته شروع می‌شود." },
      { name: "آژانس‌ها", note: "ورودی ترکیبی: ریتینر، پروژه، درخواست تک‌موردی." },
      { name: "حسابداری و حقوقی", note: "پذیرش حساس به انطباق که باید کامل باشد." },
    ],
    boundaryIntroFa: "برداشت اول تعیین می‌کند آیا درخواست‌ها مشتری می‌شوند. اتوماسیون کارِ کاغذیِ دورِ آن برداشت را انجام می‌دهد — گفتگو با شماست.",
    runsAloneFa: [
      "ثبت، ساختارمندسازی و کامل کردن اطلاعات درخواست",
      "درخواست و ردیابی اسناد",
      "ساخت CRM و مسیریابی بر اساس قوانین شما",
      "بریف داخلی قبل از اینکه کسی گوشی را بردارد",
    ],
    stopsForHumanFa: [
      "اولین گفتگوی واقعی با مشتری احتمالی",
      "تشخیص تناسبی که قوانین نمی‌توانند بیان کنند",
      "موارد پرچم‌قرمز که چشم شریک تجاری می‌خواهد",
    ],
    faqsFa: [
      { q: "اتوماسیون پذیرش مشتری چیست؟", a: "ورک‌فلویی است که هر درخواست ورودی را ثبت می‌کند، نیاز واقعی را استخراج می‌کند، اطلاعات ناقص را کامل می‌کند، در CRM فایل می‌کند و با خلاصه‌ای آماده به فرد درست ارجاع می‌دهد." },
      { q: "مشتری متوجه می‌شود با اتوماسیون حرف می‌زند؟", a: "او فقط پاسخ سریع‌تر و کامل‌تر می‌بیند. سؤال‌ها با صدای شرکت شماست و گفتگوی انسانی به محض اینکه چیزی برای گفتن هست شروع می‌شود." },
      { q: "جای فرم تماس ما را می‌گیرد؟", a: "نه — از کانال‌های فعلی تغذیه می‌کند. فرم، ایمیل و معرفی همه داخل یک فرایند پذیرش ساختاریافته می‌روند." },
      { q: "فرقش با صلاحیت‌سنجی لید چیست؟", a: "پذیرش، تبدیل درخواست‌های موجود به کارِ آماده است: کامل‌بودن، دسته‌بندی، مسیریابی. صلاحیت‌سنجی لید، prospects را علیه قوانین تناسب امتیاز و اولویت می‌دهد. بیشتر شرکت‌ها هر دو را لازم دارند." },
    ],
    seoTitleFa: "اتوماسیون پذیرش مشتری | ثبت، صلاحیت‌سنجی، ارجاع | SpielOS",
    seoDescFa: "اتوماسیون پذیرش مشتری که درخواست‌ها را ثبت، الزامات را استخراج، اسناد را جمع و درخواست‌های صلاحیت‌دار را به فرد درست ارجاع می‌کند.",
  },
  {
    slug: "document-collection-automation",
    name: "Document Collection Automation",
    eyebrow: "DOCUMENT COLLECTION AUTOMATION",
    h1: "Collect every required document without chasing anyone.",
    heroCopy:
      "Engagements stall on paperwork. SpielOS generates the exact document list per client or matter, tracks what arrived, renames and files what comes in, reminds whoever owes what, and tells you precisely what is still missing — without a single manual chase.",
    manualSteps: [
      "Compile the document list from a template — again",
      "Send the request email",
      "Wait",
      "Receive six files named scan_final(3).pdf",
      "Figure out which requirement each file satisfies",
      "Notice one is expired and two are missing",
      "Chase — carefully, so the client doesn't feel nagged",
    ],
    painPoint:
      "Document collection is pure coordination: knowing what is needed, what arrived, what is wrong with it, and who to ask — repeatedly, for every client, until everything is in.",
    beforeText:
      "A spreadsheet (or memory) tracks the checklist, and someone spends hours a week matching attachments to requirements and writing reminder emails.",
    withText:
      "Requirements are generated per engagement, incoming files are classified and filed as they arrive, gaps are chased automatically, and status is always current — visible at a glance, not reconstructed on demand.",
    flowStates: ["List generated", "Requests sent", "Files arriving", "Classified & filed", "Validity checked", "Reminders sent", "Complete confirmed"],
    flowIcons: ["bx-list-check","bx-send","bx-download","bx-category","bx-check-square","bx-bell","bx-badge"],
    automateIntro: "What document collection automation does:",
    automate: [
      { title: "Generate required document lists", desc: "Per client type, matter, or engagement — not one generic checklist." },
      { title: "Request and track documents", desc: "Received vs. missing, per requirement, always current." },
      { title: "Send smart reminders", desc: "Only for what is actually missing, phrased kindly, stopped on arrival." },
      { title: "Classify incoming files", desc: "Figures out which requirement each attachment satisfies — even badly named ones." },
      { title: "Rename and file properly", desc: "Consistent naming into the right folder in your drive, automatically." },
      { title: "Check basic requirements", desc: "Dates, signatures, completeness — obvious problems caught early." },
      { title: "Request replacements", desc: "Expired or wrong documents trigger a specific, polite re-request." },
      { title: "Report true status", desc: "One glance shows what is in, what is missing, and what is blocked." },
    ],
    toolKeys: ["gmail", "google-drive", "slack", "notion"],
    audiences: [
      { name: "Accounting firms", note: "Seasonal floods of client documents with hard deadlines." },
      { name: "Recruitment agencies", note: "CVs, IDs, contracts, certifications per placement." },
      { name: "Legal & professional services", note: "Matter-specific checklists where completeness is non-negotiable." },
    ],
    relatedWorkflows: ["client-onboarding-automation", "follow-up-automation", "client-intake-automation"],
    relatedDepartments: ["analytics", "content"],
    boundaryIntro:
      "Nobody wants a robot nagging their clients. The automation chases politely, within your tone rules — and hands over the moment a conversation is better than a reminder.",
    runsAlone: [
      "Checklist generation, requesting, and receipt tracking",
      "Classification, renaming, and filing of arrivals",
      "Basic validity checks and replacement requests",
      "Status reporting across all engagements",
    ],
    stopsForHuman: [
      "Clients who are frustrated or delayed for personal reasons",
      "Documents needing professional judgment (legality, sufficiency)",
      "Exceptions like wrong-client or wrong-engagement submissions",
    ],
    faqs: [
      { q: "What is document collection automation?", a: "It is a workflow that generates the required document list per client, requests and tracks each item, classifies and files what arrives, and automatically reminds whoever owes what until everything is complete." },
      { q: "Can it handle badly named or scanned files?", a: "Yes. Classification looks at content, not filenames — scan_final(3).pdf gets identified, renamed, and filed to the right requirement." },
      { q: "Will it spam our clients with reminders?", a: "No. Cadence and tone follow rules you set, reminders reference the specific missing item, and chasing stops the moment the document arrives or a human takes over." },
      { q: "Where do collected documents end up?", a: "Filed in your own drive structure under consistent names — plus a live status view of received vs. missing across every engagement." },
    ],
    seoTitle: "Document Collection Automation | Stop Chasing Files | SpielOS",
    seoDesc: "Document collection automation: generate per-client checklists, classify and file arrivals, chase missing items politely, see true status instantly.",
    nameFa: "اتوماسیون جمع‌آوری اسناد",
    h1Fa: "هر سند لازم را بدون تعقیب کردنِ هیچ‌کس جمع کنید.",
    heroCopyFa: "قراردادها روی کاغذبازی متوقف می‌شوند. SpielOS لیست دقیق اسناد هر مشتری یا پرونده را می‌سازد، رسیده‌ها را ردیابی می‌کند، فایل‌های ورودی را دسته‌بندی و فایل می‌کند، بدهکاران را یادآوری می‌کند و دقیقاً می‌گوید چه چیزی هنوز کم است — بدون حتی یک پیگیری دستی.",
    manualStepsFa: [
      "ساختن لیست اسناد از روی قالب — باز هم",
      "ارسال ایمیل درخواست",
      "انتظار",
      "دریافت شش فایل با اسم scan_final(3).pdf",
      "حدس زدن هر فایل کدام الزام را پر می‌کند",
      "فهمیدن اینکه یکی منقضی و دو تا گم‌اند",
      "پیگیری — با احتیاط، که مشتری حس نکند دارد اذیت می‌شود",
    ],
    painPointFa: "جمع‌آوری اسناد خالصِ هماهنگی است: دانستن چه لازم است، چه رسیده، چه ایرادی دارد و از کی بپرسیم — مکرر، برای هر مشتری، تا همه‌چیز کامل شود.",
    beforeTextFa: "یک اسپردشیت (یا حافظه) چک‌لیست را نگه می‌دارد و کسی هفته‌ای ساعت‌ها وقت صرف تطبیق پیوست‌ها با الزامات و نوشتن ایمیل یادآوری می‌کند.",
    withTextFa: "الزامات به‌ازای هر همکاری تولید می‌شوند، فایل‌های ورودی همان لحظه دسته‌بندی و فایل می‌شوند، شکاف‌ها خودکار دنبال می‌شوند و وضعیت همیشه جاری است — یک نگاه، نه بازسازی مداوم.",
    flowStatesFa: ["لیست ساخته شد","درخواست‌ها رفت","فایل‌ها رسیدند","دسته‌بندی و فایل شد","اعتبار بررسی شد","یادآوری رفت","تکمیل تأیید شد"],
    automateIntroFa: "آنچه اتوماسیون جمع‌آوری اسناد انجام می‌دهد:",
    automateFa: [
      { title: "تولید لیست اسناد موردنیاز", desc: "به‌ازای نوع مشتری، پرونده یا قرارداد — نه یک چک‌لیست عمومی." },
      { title: "درخواست و ردیابی اسناد", desc: "رسیده در برابر جاافتاده، به‌ازای هر الزام، همیشه جاری." },
      { title: "یادآوری هوشمند", desc: "فقط برای چیزی که واقعاً کم است، مؤدبانه، و متوقف با ورود سند." },
      { title: "دسته‌بندی فایل‌های ورودی", desc: "تشخیص می‌دهد هر پیوست کدام الزام را پر می‌کند — حتی با اسم‌های بد." },
      { title: "تغییر نام و فایل کردن", desc: "نام‌گذاری یکسان داخل پوشه درست در درایو شما، خودکار." },
      { title: "بررسی الزامات پایه", desc: "تاریخ، امضا، کامل‌بودن — مشکلات واضح زود گرفته می‌شوند." },
      { title: "درخواست جایگزین", desc: "اسناد منقضی یا اشتباه، درخواست مشخص و مؤدبانه برای نسخه جدید فعال می‌کنند." },
      { title: "گزارش وضعیت واقعی", desc: "یک نگاه نشان می‌دهد چه رسید، چه کم است و چه چیز بلاک شده." },
    ],
    audiencesFa: [
      { name: "دفاتر حسابداری", note: "سیل فصلی اسناد مشتریان با ضرب‌الاجل سخت." },
      { name: "آژانس‌های جذب", note: "رزومه، کارت ملی، قرارداد و مدرک برای هر placement." },
      { name: "خدمات حقوقی و حرفه‌ای", note: "چک‌لیست‌های خاص پرونده که کامل‌بودنشان قابل مذاکره نیست." },
    ],
    boundaryIntroFa: "هیچ‌کس دوست ندارد ربات تعقیبش کند. اتوماسیون مؤدبانه و داخل قوانین لحن شما پیگیری می‌کند — و لحظه‌ای که گفتگو بهتر از یادآوری است تحویل می‌دهد.",
    runsAloneFa: [
      "تولید چک‌لیست، ارسال درخواست و ردیابی دریافت",
      "دسته‌بندی، تغییر نام و فایل کردن ورودی‌ها",
      "بررسی‌های پایه اعتبار و درخواست نسخه جایگزین",
      "گزارش وضعیت در همه قراردادها",
    ],
    stopsForHumanFa: [
      "مشتریانی که عصبانی‌اند یا به دلایل شخصی تأخیر دارند",
      "اسنادی که قضاوت حرفه‌ای می‌خواهند (اعتبار، کفایت)",
      "استثناها مثل ارسال اشتباه سند یا اشتباه گرفتن قرارداد",
    ],
    faqsFa: [
      { q: "اتوماسیون جمع‌آوری اسناد چیست؟", a: "ورک‌فلویی که لیست اسناد لازم هر مشتری را می‌سازد، هر آیتم را درخواست و ردیابی می‌کند، ورودی‌ها را دسته‌بندی و فایل می‌کند و تا کامل شدن، یادآوری خودکار می‌فرستد." },
      { q: "با فایل‌های بداسم یا اسکن‌شده هم کار می‌کند؟", a: "بله. دسته‌بندی به محتوا نگاه می‌کند نه اسم فایل — scan_final(3).pdf شناسایی، تغییر نام و به الزام درست فایل می‌شود." },
      { q: "اسپم یادآوری برای مشتریان نمی‌فرستد؟", a: "نه. ریتم و لحن از قوانین شما پیروی می‌کند، یادآوری به آیتم خاص جاافتاده ارجاع می‌دهد و با رسیدن سند یا ورود انسان متوقف می‌شود." },
      { q: "اسناد جمع‌شده کجا می‌روند؟", a: "در ساختار درایو خودتان با نام‌گذاری یکسان فایل می‌شوند — به‌علاوه یک نمای زنده از رسیده/جاافتاده در همه قراردادها." },
    ],
    seoTitleFa: "اتوماسیون جمع‌آوری اسناد | پایان تعقیب فایل | SpielOS",
    seoDescFa: "اتوماسیون جمع‌آوری اسناد: چک‌لیست اختصاصی هر مشتری، دسته‌بندی و فایل ورودی‌ها، پیگیری مؤدبانه جاافتاده‌ها و دید لحظه‌ای وضعیت.",
  },
  {
    slug: "lead-qualification-automation",
    name: "Lead Qualification Automation",
    eyebrow: "LEAD QUALIFICATION AUTOMATION",
    h1: "Qualify every lead the minute it arrives — by your rules.",
    heroCopy:
      "Leads arrive faster than anyone can research them. SpielOS enriches each new lead, compares it against your qualification criteria, explains its classification, updates your CRM, and routes the promising ones onward — so hot leads get attention while they're hot.",
    manualSteps: [
      "Notice the new lead — eventually",
      "Google the company and the person",
      "Check them against fit criteria from memory",
      "Decide if they're worth a reply today",
      "Type research notes into the CRM",
      "Argue in the pipeline about which leads are real",
      "Find out the best lead of last month was never contacted",
    ],
    painPoint:
      "Qualification done from memory is inconsistent, and done slowly it is worthless. The leads that matter most are exactly the ones that won't wait.",
    beforeText:
      "Whichever lead someone gets to first gets researched; the rest age in the pipeline until someone has a spare hour that never comes.",
    withText:
      "Every lead gets the same treatment within minutes: enriched, scored against explicit criteria, classified with a stated reason, recorded, and routed — with humans making the decisions that deserve humans.",
    flowStates: ["Lead captured", "Enriched", "Criteria matched", "Scored & explained", "CRM updated", "Qualified routed", "Nurture set"],
    flowIcons: ["bx-user-plus","bx-search","bx-target-lock","bx-bar-chart-alt-2","bx-data","bx-send","bx-time-five"],
    automateIntro: "What lead qualification automation delivers:",
    automate: [
      { title: "Capture leads from every channel", desc: "Forms, inbound email, outbound replies — one pipeline." },
      { title: "Research company and person", desc: "Public signals gathered and summarized where it helps the decision." },
      { title: "Enrich existing information", desc: "Fill gaps in the record before scoring, not during the sales call." },
      { title: "Compare against your criteria", desc: "Explicit, editable qualification rules — not a black-box score." },
      { title: "Identify missing information", desc: "Flags what would change the classification and asks for it." },
      { title: "Score and categorize", desc: "Tiered, with the reason written out in plain language." },
      { title: "Update CRM and route", desc: "Qualified leads reach the right owner immediately, with context." },
      { title: "Trigger the right follow-up", desc: "Qualified gets outreach; nurture track gets patience; poor fit gets closure." },
    ],
    toolKeys: ["attio", "hubspot", "gmail", "telegram", "slack"],
    audiences: [
      { name: "B2B service businesses", note: "Fit depends on size, sector, and need — not gut feel." },
      { name: "Agencies with inbound", note: "Inquiry volume outruns manual research capacity." },
      { name: "Founders doing sales themselves", note: "Qualification happens at midnight or not at all." },
    ],
    relatedWorkflows: ["client-intake-automation", "follow-up-automation", "data-entry-automation"],
    relatedDepartments: ["marketing", "analytics"],
    boundaryIntro:
      "AI should explain, not decide your pipeline. Classification comes with reasons; irreversible choices — pursuing, pricing, discarding — stay with you.",
    runsAlone: [
      "Enrichment, criteria matching, and tiered classification",
      "Written explanations for every classification",
      "CRM updates and routing to owners",
      "Standard follow-up triggers per tier",
    ],
    stopsForHuman: [
      "Final pursuit decisions and pricing conversations",
      "Borderline fits where strategy matters more than rules",
      "Anything resembling an automated yes/no on a real relationship",
    ],
    faqs: [
      { q: "What is lead qualification automation?", a: "It enriches every incoming lead, compares it against your explicit qualification criteria, classifies it with a written explanation, updates your CRM, and routes qualified leads to the right owner immediately." },
      { q: "Will AI decide which leads we pursue?", a: "No. It classifies and explains; your team makes the pursue-or-pass decision. That boundary is deliberate — qualification informs judgment, it doesn't replace it." },
      { q: "Can we define our own criteria?", a: "Yes — criteria are explicit and editable: size, sector, need, geography, signal, whatever actually predicts fit in your business." },
      { q: "How fast does a new lead get qualified?", a: "Minutes, not days. The point is that hot leads get attention while they're still hot." },
    ],
    seoTitle: "Lead Qualification Automation | Score, Explain, Route | SpielOS",
    seoDesc: "Lead qualification automation that enriches every lead, scores it against your criteria with reasons, updates the CRM, and routes hot leads fast.",
    nameFa: "اتوماسیون صلاحیت‌سنجی لید",
    h1Fa: "هر لید را لحظه ورود، با قوانین خودتان صلاحیت‌سنجی کنید.",
    heroCopyFa: "لیدها سریع‌تر از توان تحقیق هر کسی می‌رسند. SpielOS هر لید جدید را غنی‌سازی می‌کند، با معیارهای صلاحیت شما مقایسه می‌کند، دلیل طبقه‌بندی‌اش را توضیح می‌دهد، CRM را به‌روز می‌کند و لیدهای امیدوارکننده را مسیریابی می‌کند — تا لیدهای داغ وقتی داغ‌اند توجه بگیرند.",
    manualStepsFa: [
      "متوجه شدن لید جدید — بالاخره",
      "گوگل کردن شرکت و شخص",
      "چک کردن معیارهای تناسب از حفظ",
      "تصمیم اینکه امروز ارزش پاسخ دادن دارد یا نه",
      "تایپ یادداشت‌های تحقیق داخل CRM",
      "دعوا در پایپ‌لاین اینکه کدام لید واقعی است",
      "فهمیدن بهترین لید ماه پیش هرگز تماس نگرفته",
    ],
    painPointFa: "صلاحیت‌سنجی از روی حافظه ناسازگار است و اگر کند باشد بی‌ارزش. لیدهایی که بیشترین اهمیت را دارند دقیقاً همین‌هایی هستند که منتظر نمی‌مانند.",
    beforeTextFa: "لیدی که اول به دستش برسد تحقیق می‌شود؛ بقیه در پایپ‌لاین پیر می‌شوند تا ساعت آزادی برسد که هرگز نمی‌رسد.",
    withTextFa: "هر لید ظرف چند دقیقه همان treatment را می‌گیرد: غنی‌سازی، امتیازدهی علیه معیارهای صریح، طبقه‌بندی با دلیل نوشته‌شده، ثبت و مسیریابی — با تصمیم‌های انسانی برای مواردی که انسان می‌خواهند.",
    flowStatesFa: ["لید ثبت شد","غنی‌سازی شد","معیارها تطبیق یافت","امتیاز و توضیح داده شد","CRM به‌روز شد","صلاحیت‌دار مسیریابی شد","Nurture تنظیم شد"],
    automateIntroFa: "آنچه اتوماسیون صلاحیت‌سنجی لید تحویل می‌دهد:",
    automateFa: [
      { title: "ثبت لید از هر کانالی", desc: "فرم، ایمیل ورودی، پاسخ‌های برون‌سپاری — یک خط لوله." },
      { title: "تحقیق شرکت و شخص", desc: "جمع‌آوری و خلاصه سیگنال‌های عمومی جایی که به تصمیم کمک می‌کند." },
      { title: "غنی‌سازی اطلاعات موجود", desc: "پر کردن خلأهای رکورد قبل از امتیازدهی، نه وسط تماس فروش." },
      { title: "تطبیق با معیارهای شما", desc: "قوانین صریح و قابل‌ویرایش — نه امتیاز جعبه‌سیاه." },
      { title: "شناسایی اطلاعات جاافتاده", desc: "علامت‌گذاری چیزی که طبقه‌بندی را عوض می‌کرد و پرسیدنش." },
      { title: "امتیاز و دسته‌بندی", desc: "سطح‌بندی‌شده، با دلیل نوشته‌شده به زبان ساده." },
      { title: "به‌روزرسانی CRM و مسیریابی", desc: "لیدهای صلاحیت‌دار فوراً با بافت کامل به مالک می‌رسند." },
      { title: "فعال‌سازی پیگیری مناسب", desc: "صلاحیت‌دار outreach می‌گیرد؛ مسیر nurture صبر؛ تناسب ضعیف بسته می‌شود." },
    ],
    audiencesFa: [
      { name: "کسب‌وکارهای خدماتی B2B", note: "تناسب به اندازه، صنعت و نیاز بستگی دارد — نه شهود." },
      { name: "آژانس‌های دارای inbound", note: "حجم درخواست‌ها از ظرفیت تحقیق دستی جلوتر است." },
      { name: "بنیانگذارانی که خودشان فروش می‌کنند", note: "صلاحیت‌سنجی نصف شب اتفاق می‌افتد یا اصلاً نمی‌افتد." },
    ],
    boundaryIntroFa: "AI باید توضیح دهد، نه پایپ‌لاین شما را اداره کند. طبقه‌بندی همراه با دلیل می‌آید؛ تصمیم‌های برگشت‌ناپذیر — پیگیری، قیمت‌گذاری، کنار گذاشتن — با شما می‌مانند.",
    runsAloneFa: [
      "غنی‌سازی، تطبیق معیارها و طبقه‌بندی سطح‌بندی‌شده",
      "توضیح مکتوب برای هر طبقه‌بندی",
      "به‌روزرسانی CRM و مسیریابی به مالکان",
      "تریگرهای استاندارد پیگیری برای هر سطح",
    ],
    stopsForHumanFa: [
      "تصمیم نهایی پیگیری و مذاکرات قیمت",
      "تناسب‌های مرزی که استراتژی مهم‌تر از قوانین است",
      "هر چیزی شبیه بله/خیر خودکار روی یک رابطه واقعی",
    ],
    faqsFa: [
      { q: "اتوماسیون صلاحیت‌سنجی لید چیست؟", a: "هر لید ورودی را غنی می‌کند، با معیارهای صریح شما مقایسه می‌کند، با توضیح مکتوب طبقه‌بندی می‌کند، CRM را به‌روز می‌کند و لیدهای صلاحیت‌دار را فوراً به مالک می‌رساند." },
      { q: "آیا AI تصمیم می‌گیرد کدام لیدها را دنبال کنیم؟", a: "نه. طبقه‌بندی و توضیح می‌دهد؛ تیم شما تصمیم پیگیری یا رد را می‌گیرد. این مرز عمدی است — صلاحیت‌سنجی به قضاوت کمک می‌کند، جای آن را نمی‌گیرد." },
      { q: "می‌توانیم معیارهای خودمان را تعریف کنیم؟", a: "بله — معیارها صریح و قابل‌ویرایش‌اند: اندازه، صنعت، نیاز، جغرافیا، سیگنال، هر چیزی که واقعاً تناسب را پیش‌بینی می‌کند." },
      { q: "لید جدید چند طول می‌کشد صلاحیت‌سنجی شود؟", a: "دقیقه‌ها، نه روزها. نکته همین است: لیدهای داغ وقتی داغ‌اند توجه بگیرند." },
    ],
    seoTitleFa: "اتوماسیون صلاحیت‌سنجی لید | امتیاز، توضیح، مسیریابی | SpielOS",
    seoDescFa: "اتوماسیون صلاحیت‌سنجی لید که هر لید را غنی می‌کند، با معیارهای شما امتیاز و دلیل می‌دهد، CRM را به‌روز می‌کند و لیدهای داغ را سریع مسیریابی می‌کند.",
  },
  {
    slug: "invoice-processing-automation",
    name: "Invoice Processing Automation",
    eyebrow: "INVOICE PROCESSING AUTOMATION",
    h1: "From invoice in the inbox to accounting-ready entry — without retyping.",
    heroCopy:
      "Supplier invoices arrive as PDFs and emails and become somebody's typing job. SpielOS receives them, extracts the fields, checks them for duplicates and consistency, prepares the accounting entry, and queues approval — with the original document and full history kept.",
    manualSteps: [
      "Download the attachment from email",
      "Read supplier, date, amounts, line items off the PDF",
      "Retype them into the accounting system",
      "Hunt through history to check it isn't a duplicate",
      "Match it to the right client, project, or cost center",
      "Chase approval from whoever owns the spend",
      "File the PDF somewhere findable — hopefully",
    ],
    painPoint:
      "Invoice processing is high-stakes typing: repetitive enough to breed carelessness, important enough that errors cost real money and credibility with accountants.",
    beforeText:
      "Each invoice is processed by hand end-to-end, with correctness depending on focus and duplicates depending on luck.",
    withText:
      "Invoices flow from inbox to accounting-ready draft automatically: fields extracted and validated, duplicates caught, matches proposed, approvals routed — and every entry traceable to its source document.",
    flowStates: ["Invoice received", "Fields extracted", "Checks passed", "Duplicates rejected", "Entry prepared", "Approval routed", "History archived"],
    flowIcons: ["bx-download","bx-search-alt","bx-check-square","bx-copy","bx-receipt","bx-user-check","bx-archive"],
    automateIntro: "What invoice processing automation covers:",
    automate: [
      { title: "Receive invoices from email", desc: "Attachments and forwarded bills captured into one processing pipeline." },
      { title: "Extract supplier and invoice fields", desc: "Vendor, dates, totals, VAT, line items — read from PDFs and scans." },
      { title: "Validate required information", desc: "Incomplete or malformed invoices flagged before they pollute accounting." },
      { title: "Detect duplicates", desc: "Cross-checked against history so nothing is booked or paid twice." },
      { title: "Match to existing records", desc: "Proposed links to purchase orders, clients, projects, or cost centers." },
      { title: "Prepare accounting entries", desc: "Drafts formatted for your accounting system — reviewed, then posted." },
      { title: "Route exceptions and approvals", desc: "Oddities go to the right reviewer; normal ones to routine approval." },
      { title: "Preserve documents and history", desc: "Original file plus every processing decision, permanently attached." },
    ],
    toolKeys: ["gmail", "google-drive", "slack", "notion"],
    audiences: [
      { name: "Small finance teams", note: "Bookkeeping capacity spent on typing, not reviewing." },
      { name: "Agencies & service firms", note: "Project-level cost tracking needs accurate invoice matching." },
      { name: "Businesses scaling past spreadsheets", note: "Volume broke the manual process months ago." },
    ],
    relatedWorkflows: ["data-entry-automation", "document-collection-automation", "follow-up-automation"],
    relatedDepartments: ["analytics"],
    boundaryIntro:
      "Money moves with approval, not automation. The system prepares everything and enforces the checkpoint — a human approves before anything posts.",
    runsAlone: [
      "Capture, extraction, validation, and duplicate detection",
      "Matching proposals and accounting-ready drafts",
      "Approval routing with full context attached",
      "Archiving originals with processing history",
    ],
    stopsForHuman: [
      "Every posting — approval is a human gate, always",
      "Mismatched amounts, unknown suppliers, and exceptions",
      "Payment execution, which stays entirely outside automation",
    ],
    faqs: [
      { q: "What is invoice processing automation?", a: "It reads incoming invoices, extracts and validates the fields, checks for duplicates, proposes matches, prepares the accounting entry, and routes it for approval — with the original document and full audit trail preserved." },
      { q: "Does AI approve payments automatically?", a: "No. Nothing posts or pays without a human approving it. Automation prepares and organizes; the financial checkpoint stays with your team." },
      { q: "Which accounting systems does it work with?", a: "Entries are prepared for your existing accounting workflow — your accountant or bookkeeper reviews and posts as usual, now from clean drafts instead of retyped numbers." },
      { q: "How are duplicate invoices detected?", a: "Each invoice is cross-checked against processing history on supplier, number, amount, and date. Suspected duplicates are held with both documents side by side." },
    ],
    seoTitle: "Invoice Processing Automation | Inbox to Accounting-Ready | SpielOS",
    seoDesc: "Invoice processing automation: extract fields, catch duplicates, match records, prepare accounting entries, route approvals — humans approve, always.",
    nameFa: "اتوماسیون پردازش فاکتور",
    h1Fa: "از فاکتور داخل ایمیل تا ثبتِ آماده‌ی حسابداری — بدون تایپ مجدد.",
    heroCopyFa: "فاکتورهای تأمین‌کننده به‌شکل PDF و ایمیل می‌رسند و کارِ تایپ کسی می‌شوند. SpielOS آن‌ها را دریافت، فیلدها را استخراج، از نظر تکرار و سازگاری بررسی، ثبتِ حسابداری را آماده و تأیید را مسیریابی می‌کند — با نگه‌داشتن سند اصلی و تاریخچه کامل.",
    manualStepsFa: [
      "دانلود پیوست از ایمیل",
      "خواندن تأمین‌کننده، تاریخ، مبالغ و ردیف‌ها از PDF",
      "تایپ دوباره در سیستم حسابداری",
      "جستجوی تاریخچه برای چک تکراری‌بودن",
      "تطبیق با مشتری، پروژه یا مرکز هزینه درست",
      "دویدن دنبال تأیید مالکِ هزینه",
      "فایل کردن PDF جایی که بعداً پیدا شود — امیدوارانه",
    ],
    painPointFa: "پردازش فاکتور تایپیِ پرمخاطره است: آن‌قدر تکراری که بی‌دقتی می‌آورد و آن‌قدر مهم که خطایش پول واقعی و اعتبار نزد حسابدار می‌گیرد.",
    beforeTextFa: "هر فاکتور سرتاسری دستی پردازش می‌شود؛ درستی‌اش به تمرکز بستگی دارد و تشخیص تکراری به شانس.",
    withTextFa: "فاکتورها خودکار از ایمیل تا پیش‌نویس حسابداری جریان پیدا می‌کنند: استخراج و اعتبارسنجی فیلدها، گرفتن تکراری‌ها، پیشنهاد تطبیق، مسیریابی تأیید — و هر ثبت قابل ردیابی به سند منبع.",
    flowStatesFa: ["فاکتور رسید","فیلدها استخراج شد","بررسی‌ها پاس شد","تکراری‌ها رد شد","ثبت آماده شد","تأیید مسیریابی شد","تاریخچه بایگانی شد"],
    automateIntroFa: "آنچه اتوماسیون پردازش فاکتور پوشش می‌دهد:",
    automateFa: [
      { title: "دریافت فاکتورها از ایمیل", desc: "پیوست‌ها و قبض‌های فورواردی در یک خط لوله پردازش." },
      { title: "استخراج فیلدهای تأمین‌کننده و فاکتور", desc: " فروشنده، تاریخ، جمع کل، مالیات، ردیف‌ها — از PDF و اسکن." },
      { title: "اعتبارسنجی اطلاعات الزامی", desc: "فاکتورهای ناقص قبل از آلوده کردن حسابداری علامت می‌خورند." },
      { title: "تشخیص تکراری‌ها", desc: "با تاریخچه چک می‌شود تا چیزی دو بار ثبت یا پرداخت نشود." },
      { title: "تطبیق با رکوردهای موجود", desc: "پیشنهاد لینک به سفارش خرید، مشتری، پروژه یا مرکز هزینه." },
      { title: "آماده‌سازی ثبتهای حسابداری", desc: "پیش‌نویس‌ها فرمت‌شده برای سیستم حسابداری شما — بازبینی، سپس ثبت." },
      { title: "مسیریابی استثنا و تأیید", desc: "موارد عجیب به بازبین درست؛ موارد عادی به تأیید معمول." },
      { title: "حفظ اسناد و تاریخچه", desc: "فایل اصلی به‌علاوه همه تصمیمات پردازش، همیشه پیوست." },
    ],
    audiencesFa: [
      { name: "تیم‌های مالی کوچک", note: "ظرفیت حسابداری صرف تایپ می‌شود نه بازبینی." },
      { name: "آژانس‌ها و شرکت‌های خدماتی", note: "ردیابی هزینه پروژه به تطبیق دقیق فاکتور نیاز دارد." },
      { name: "کسب‌وکارهایی که از شیت بزرگ شدند", note: "حجم ماه‌ها پیش فرایند دستی را شکسته." },
    ],
    boundaryIntroFa: "پول با تأیید حرکت می‌کند، نه با اتوماسیون. سیستم همه‌چیز را آماده می‌کند و ایستگاه را اجباری نگه می‌دارد — یک انسان قبل از هر ثبت تأیید می‌کند.",
    runsAloneFa: [
      "دریافت، استخراج، اعتبارسنجی و تشخیص تکراری",
      "پیشنهاد تطبیق و پیش‌نویس آماده حسابداری",
      "مسیریابی تأیید با بافت کامل",
      "بایگانی اصل سند با تاریخچه پردازش",
    ],
    stopsForHumanFa: [
      "هر ثبت — تأیید همیشه گیت انسانی است",
      "مبالغ ناهمخوان، تأمین‌کننده ناشناس و استثناها",
      "اجرای پرداخت که کلاً بیرون از اتوماسیون می‌ماند",
    ],
    faqsFa: [
      { q: "اتوماسیون پردازش فاکتور چیست؟", a: "فاکتورهای ورودی را می‌خواند، فیلدها را استخراج و اعتبارسنجی می‌کند، تکراری‌ها را می‌گیرد، تطبیق پیشنهاد می‌دهد، ثبت حسابداری را آماده و برای تأیید مسیریابی می‌کند — با حفظ سند اصلی و ردیابی کامل." },
      { q: "AI پرداخت‌ها را خودکار تأیید می‌کند؟", a: "نه. هیچ چیزی بدون تأیید انسان ثبت یا پرداخت نمی‌شود. اتوماسیون آماده و سازماندهی می‌کند؛ گیت مالی با تیم شماست." },
      { q: "با کدام سیستم‌های حسابداری کار می‌کند؟", a: "ثبت‌ها برای گردش کار فعلی حسابداری شما آماده می‌شوند — حسابدار همان‌طور که همیشه بوده بازبینی و ثبت می‌کند، این بار از روی پیش‌نویس تمیز به‌جای اعداد تایپ‌شده." },
      { q: "فاکتور تکراری چطور تشخیص داده می‌شود؟", a: "هر فاکتور روی تأمین‌کننده، شماره، مبلغ و تاریخ با تاریخچه چک می‌شود. مشکوک‌ها با هر دو سند کنار هم نگه داشته می‌شوند." },
    ],
    seoTitleFa: "اتوماسیون پردازش فاکتور | از ایمیل تا حسابداری | SpielOS",
    seoDescFa: "اتوماسیون پردازش فاکتور: استخراج فیلدها، گرفتن تکراری‌ها، تطبیق رکوردها، آماده‌سازی ثبت حسابداری و مسیریابی تأیید — تأیید همیشه با انسان.",
  },
  {
    slug: "candidate-screening-automation",
    name: "Candidate Screening Automation",
    eyebrow: "CANDIDATE SCREENING AUTOMATION",
    h1: "Screen every applicant properly — before recruiters burn their day.",
    heroCopy:
      "Applications pile up faster than anyone can read them properly. SpielOS reads each CV, extracts the facts that matter, compares them against the role's explicit criteria, prepares honest candidate summaries, and ranks them for recruiter review — so human judgment starts from a shortlist, not an inbox.",
    manualSteps: [
      "Open application #47 of the day",
      "Skim the CV looking for the must-haves",
      "Try to remember what role this even was",
      "Copy basics into the ATS inconsistently",
      "Write rough notes you'll disagree with later",
      "Shortlist based on who you saw most recently",
      "Lose good candidates in the pile because fatigue won",
    ],
    painPoint:
      "Screening volume punishes thoroughness. Read every CV properly and you drown; skim and the best candidates vanish into the pile. Fatigue, not judgment, makes the cut.",
    beforeText:
      "Recruiters triage applications in stolen minutes between calls — and screening quality depends on what time of day it is.",
    withText:
      "Every application gets the same careful read: structured extraction, explicit-criteria comparison, a factual summary, and a ranking that explains itself. Recruiters spend their time judging shortlisted humans, not formatting chaos.",
    flowStates: ["Application in", "Facts extracted", "Criteria compared", "Summary prepared", "Ranked for review", "ATS updated", "Next steps triggered"],
    flowIcons: ["bx-envelope-open","bx-search-alt","bx-target-lock","bx-file","bx-bar-chart-alt-2","bx-data","bx-calendar"],
    automateIntro: "What candidate screening automation does:",
    automate: [
      { title: "Read applications and CVs", desc: "All formats — including the creative ones recruiters dread." },
      { title: "Extract structured profiles", desc: "Experience, skills, locations, rights to work, education — as clean data." },
      { title: "Compare against explicit criteria", desc: "The role's real must-haves and nice-to-haves, defined by the recruiter." },
      { title: "Retrieve relevant past candidates", desc: "Surfaces previous applicants who now fit a new role." },
      { title: "Prepare candidate summaries", desc: "Factual, comparable briefs: what they've done against what the role needs." },
      { title: "Rank for recruiter review", desc: "Ordered shortlists with reasoning — never an opaque score." },
      { title: "Update the ATS or CRM", desc: "Consistent records created for every applicant automatically." },
      { title: "Coordinate next steps", desc: "Interview scheduling and status follow-ups handled by the workflow." },
    ],
    toolKeys: ["gmail", "google-drive", "slack", "google-calendar", "notion"],
    audiences: [
      { name: "Recruitment agencies", note: "Screening volume is the business model's bottleneck." },
      { name: "Internal recruiting teams", note: "Roles open for weeks because review lags applications." },
      { name: "Staffing businesses", note: "Fast, consistent screening across many simultaneous roles." },
    ],
    relatedWorkflows: ["follow-up-automation", "data-entry-automation", "document-collection-automation"],
    relatedDepartments: ["marketing"],
    boundaryIntro:
      "Hiring decisions change lives, so they stay human — completely. The automation reads and organizes; recruiters evaluate, interview, and decide.",
    runsAlone: [
      "Reading, extraction, criteria comparison, and summarizing",
      "Ranking with transparent reasoning for review",
      "ATS record creation and status upkeep",
      "Screening-stage communication logistics",
    ],
    stopsForHuman: [
      "Every hiring decision, interview, and rejection",
      "Judgment about culture, potential, and fit beyond criteria",
      "Any candidate communication that carries good or bad news",
    ],
    faqs: [
      { q: "What is candidate screening automation?", a: "It reads every application, extracts structured candidate facts, compares them against the role's explicit criteria, prepares comparable summaries, and ranks them for recruiter review — so recruiters judge a shortlist instead of an inbox." },
      { q: "Does AI make hiring decisions?", a: "Never. It organizes and summarizes; recruiters make every decision. Ranking exists to direct attention, and its reasoning is always visible." },
      { q: "How is bias handled?", a: "Comparisons run only against the explicit, job-related criteria you define. Summaries are factual rather than evaluative, and humans review every recommendation before anything happens to a candidacy." },
      { q: "Does it work with our ATS?", a: "It creates and maintains consistent candidate records in the systems you use; deep ATS integrations are added where genuinely supported rather than claimed generically." },
    ],
    seoTitle: "Candidate Screening Automation | Shortlists, Not Piles | SpielOS",
    seoDesc: "Candidate screening automation: read every CV, compare against role criteria, prepare summaries, rank for recruiters. Hiring decisions stay human.",
    nameFa: "اتوماسیون غربالگری کاندید",
    h1Fa: "هر متقاضی را درست غربالگری کنید — قبل از اینکه روزِ ریکروتر بسوزد.",
    heroCopyFa: "درخواست‌ها سریع‌تر از توان خواندنِ درست جمع می‌شوند. SpielOS هر CV را می‌خواند، حقایق مهم را استخراج، با معیارهای صریح نقش مقایسه، خلاصه‌های صادقانه آماده و برای بازبینی ریکروتر رتبه‌بندی می‌کند — تا قضاوت انسانی از یک لیست کوتاه شروع شود، نه از یک اینباکس.",
    manualStepsFa: [
      "باز کردن درخواست شماره ۴۷ امروز",
      "مرور CV برای یافتن الزامات اصلی",
      "یادآوری اینکه اصلاً این مال کدام نقش بود",
      "کپی ناقص اطلاعات پایه در ATS",
      "نوشتن یادداشت‌های خام که بعداً با آن‌ها مخالف خواهید بود",
      "لیست کوتاه بر اساس آخرین نفراتی که دیدید",
      "گم شدن کاندیدهای خوب در تلنبار شدن و خستگی",
    ],
    painPointFa: "حجمِ غربالگری به دقت جریمه می‌دهد. اگر همه CVها را کامل بخوانید غرق می‌شوید؛ اگر مرور کنید بهترین کاندیدها در تلنبار گم می‌شوند. خستگی تعیین می‌کند، نه قضاوت.",
    beforeTextFa: "ریکروترها بین تماس‌ها، در دقایق دزدی، درخواست‌ها را triage می‌کنند — و کیفیت غربالگری به ساعتِ روز بستگی دارد.",
    withTextFa: "هر درخواست همان خواندنِ دقیق را می‌گیرد: استخراج ساختاریافته، مقایسه با معیارهای صریح، خلاصه factual و رتبه‌بندی خودتوضیح. ریکروتر وقتشان را صرف قضاوت درباره انسان‌های لیست کوتاه می‌کنند، نه مرتب‌سازی هرج‌ومرج.",
    flowStatesFa: ["درخواست رسید","حقایق استخراج شد","معیارها مقایسه شد","خلاصه آماده شد","برای بازبینی رتبه شد","ATS به‌روز شد","قدم بعد فعال شد"],
    automateIntroFa: "آنچه اتوماسیون غربالگری کاندید انجام می‌دهد:",
    automateFa: [
      { title: "خواندن درخواست‌ها و CVها", desc: "همه فرمت‌ها — حتی خلاقانی که ریکروترها از آن‌ها می‌ترسند." },
      { title: "استخراج پروفایل ساختاریافته", desc: "تجربه، مهارت، موقعیت، حق کار، تحصیلات — به‌شکل داده تمیز." },
      { title: "مقایسه با معیارهای صریح", desc: "الزامات واقعی نقش و موارد nice-to-have، تعریف‌شده توسط ریکروتر." },
      { title: "بازیابی کاندیدهای مرتبط قبلی", desc: "متقاضیان قبلی که حالا برای نقش جدید مناسب شده‌اند." },
      { title: "آماده‌سازی خلاصه کاندید", desc: "بریف‌های factual و قابل‌مقایسه: چه کرده‌اند مقابل چه لازم است." },
      { title: "رتبه‌بندی برای بازبینی ریکروتر", desc: "لیست کوتاه ترتیبی با دلیل شفاف — هرگز امتیاز مبهم." },
      { title: "به‌روزرسانی ATS یا CRM", desc: "رکورد یکسان برای هر متقاضی به‌طور خودکار ساخته می‌شود." },
      { title: "هماهنگی قدم‌های بعدی", desc: "زمان‌بندی مصاحبه و پیگیری وضعیت با همین ورک‌فلو انجام می‌شود." },
    ],
    audiencesFa: [
      { name: "آژانس‌های جذب", note: "حجم غربالگری گلوگاه مدل کسب‌وکار است." },
      { name: "تیم‌های استخدام داخلی", note: "نقش‌ها هفته‌ها باز می‌مانند چون بازبینی از درخواست‌ها عقب است." },
      { name: "کسب‌وکارهای staffing", note: "غربالگری سریع و یکسان در چندین نقش موازی." },
    ],
    boundaryIntroFa: "تصمیم استخدام سرنوشت آدم‌هاست، پس کاملاً انسانی می‌ماند. اتوماسیون می‌خواند و سازماندهی می‌کند؛ ریکروتر ارزیابی، مصاحبه و تصمیم می‌گیرد.",
    runsAloneFa: [
      "خواندن، استخراج، مقایسه معیارها و خلاصه‌سازی",
      "رتبه‌بندی با دلیل شفاف برای بازبینی",
      "ساخت رکورد ATS و نگهداری وضعیت",
      "لجستیک ارتباطات مرحله غربالگری",
    ],
    stopsForHumanFa: [
      "هر تصمیم استخدام، مصاحبه و رد کردن",
      "قضاوت درباره فرهنگ، پتانسیل و تناسب فراتر از معیارها",
      "هر ارتباط با کاندید که خبر خوب یا بد حمل می‌کند",
    ],
    faqsFa: [
      { q: "اتوماسیون غربالگری کاندید چیست؟", a: "هر درخواست را می‌خواند، حقایق ساختاریافته کاندید را استخراج، با معیارهای صریح نقش مقایسه، خلاصه‌های قابل‌مقایسه آماده و برای بازبینی ریکروتر رتبه‌بندی می‌کند — تا ریکروتر به‌جای اینباکس، لیست کوتاه را قضاوت کند." },
      { q: "آیا AI تصمیم استخدام می‌گیرد؟", a: "هرگز. سازماندهی و خلاصه می‌کند؛ هر تصمیم با ریکروتر است. رتبه‌بندی فقط جهت‌دهی توجه است و دلیلش همیشه قابل مشاهده است." },
      { q: "با سوگیری (bias) چطور برخورد می‌شود؟", a: "مقایسه فقط علیه معیارهای صریح و مرتبط با شغل اجرا می‌شود. خلاصه‌ها توصیفی‌اند نه ارزیابانه، و هر پیشنهاد قبل از هر اقدامی توسط انسان بازبینی می‌شود." },
      { q: "با ATS ما کار می‌کند؟", a: "رکوردهای یکسان کاندید را در سیستم‌های فعلی شما می‌ساخت و نگه می‌دارد؛ integration عمیق با ATS جایی که واقعاً پشتیبانی می‌شود اضافه می‌گردد، نه ادعای کلی." },
    ],
    seoTitleFa: "اتوماسیون غربالگری کاندید | لیست کوتاه، نه تلنبار | SpielOS",
    seoDescFa: "اتوماسیون غربالگری کاندید: خواندن هر CV، مقایسه با معیارهای نقش، خلاصه‌سازی و رتبه‌بندی برای ریکروتر. تصمیم استخدام انسانی می‌ماند.",
  },
];

/** Hub groupings — organized by the actual work, not alphabetically. */
export const WORKFLOW_HUB_GROUPS: { id: string; label: string; blurb: string; slugs: string[] }[] = [
  { id: "chasing", label: "Chasing", blurb: "Work that stalls because someone has to remember to ask.", slugs: ["follow-up-automation", "document-collection-automation"] },
  { id: "moving", label: "Moving information", blurb: "Copying, checking, and re-entering the same data.", slugs: ["data-entry-automation", "client-intake-automation", "invoice-processing-automation"] },
  { id: "deciding", label: "Deciding & routing", blurb: "Sorting what arrived so the right person acts on it.", slugs: ["lead-qualification-automation", "candidate-screening-automation"] },
  { id: "running", label: "Running processes", blurb: "Multi-step sequences that repeat for every client.", slugs: ["client-onboarding-automation"] },
];
